- rp2040-hal/src/lib.rs
- rp2040-hal/src/rom_data.rs
Exposes rom funcs and rom data.
> Add rom stuff

- rp2040-hal/src/xosc.rs
XOSC branch had a warning in build which caused CI to fail.
Also wasn't formatted with cargo fmt, so I've done that as well.
> Remove unnecessary unsafe block + cargo fmt XOSC

- rp2040-hal/src/clocks/macros.rs
- rp2040-hal/src/clocks/mod.rs
- rp2040-hal/src/lib.rs
> Clocks (based on #31 by Nic0w), fixed merge conflict, clippy, fmt

- rp2040-hal/src/gpio.rs
The sio argument does not work with a bare pac SIO struct
> Fix gpio docs

- rp2040-hal/src/clocks/macros.rs
- rp2040-hal/src/clocks/mod.rs
Also reorderd the macro invocations to match the datasheet
> Add missing clocks

- rp2040-hal/src/rom_data.rs
Most of the functions provided in `rom_data` can do unsafe things.
You can use `memset`/friends to modify Rust data structures without limits. It is safe Rust to get a raw (const or not) pointer to something, and it is also safe Rust to turn a `*const T` into a `*mut T`. It is only unsafe to dereference the raw pointer.
Any operations from the ROM that allow pointer operations on memory (ergo a "dereference") should be unsafe.
I believe the operations that change how the flash is set up should also be considered unsafe, as those may cause undefined behavior in the code (especially, but not only, if you are using the QSPI pins as GPIO.)
`wait_for_vector` has some preconditions for when it should be used, so should probably be unsafe as well.
I see no unsafe behavior from `popcount32`, …
> split rom_data into safe and unsafe functions

- rp2040-hal/src/clocks/macros.rs
- rp2040-hal/src/clocks/mod.rs
- rp2040-hal/src/pll.rs
Preliminary init function to setup the clocks the same as the C SDK does. I am not sure about the structure but at least it gets everything going...
> Clock init

- rp2040-hal/src/clocks/available_clocks.rs
- rp2040-hal/src/clocks/macros.rs
- rp2040-hal/src/clocks/mod.rs
- rp2040-hal/src/lib.rs
- rp2040-hal/src/pll.rs
- rp2040-hal/src/rosc.rs
This makes setting clocks much safer and easier
Still to do for a next change is to give the clocks some type state so you cannot change a clock if there are dependents (or they change automatically as well)
Closes #47
> Refactor clocks

- rp2040-hal/Cargo.toml
- rp2040-hal/examples/lcd_display.rs
I think this is a good example showing how to use libraries compatible with embedded-hal.
Make sure to squash commits, I forgot to format.
Also, is there a better way to get the AHL bus speed from the HAL?
> Add HD44780 example

- Cargo.toml
- boards/adafruit_macropad/Cargo.toml
- boards/adafruit_macropad/src/lib.rs
https://www.adafruit.com/product/5100
Prefixing the package with 'adafruit' as "Macropad" is a fairly generic term
> Add Adafruit Macropad BSP

- rp2040-hal/src/clocks/mod.rs
Resolves #72 by applying suggested edits
> Correctly configure watchdog tick generation

- .github/workflows/check.yml
- rp2040-hal/src/clocks/mod.rs
- rp2040-hal/src/gpio/dynpin.rs
- rp2040-hal/src/gpio/pin.rs
- rp2040-hal/src/pwm.rs
- rp2040-hal/src/sio.rs
- rp2040-hal/src/spi.rs
- rp2040-hal/src/uart.rs
> Fix doc examples and add checking

- rp2040-hal/src/gpio/mod.rs
> Add doc example for gpio

- rp2040-hal/examples/adc.rs
- rp2040-hal/src/adc.rs
> Add ADC example and doc-example

- rp2040-hal/src/adc.rs
Wait for the adc to complete the read before reading the resault
> Fix adc giving wrong values on sequential reads of multiple channels

- Cargo.toml
- boards/pro_micro_rp2040/Cargo.toml
- boards/pro_micro_rp2040/examples/pro_micro_rainbow.rs
- boards/pro_micro_rp2040/src/lib.rs
Everything is in the title.
It has a dependency on https://github.com/ithinuel/ws2812-pio-rs.
> Add Pro Micro rainbow example (uses PIO & Timer's Countdown)

- rp2040-hal/examples/spi.rs
> Add basic SPI example

- rp2040-hal/src/i2c.rs
> Add doc example for i2c

- rp2040-hal/src/pwm/mod.rs
Previously only channel b could be inverted.
> Fix PWM set_inverted/clr_inverted

- CODE_OF_CONDUCT.md
- README.md
Also copy in the full CoC from REWG.
> Update README with examples

- rp2040-hal/examples/pio_blink.rs
Just a simple blinky, this time implemented using PIO.
This fixes #114.
> Add a simple example for PIO.

- boards/pico/examples/pico_countdown_blinky.rs
- boards/pico/examples/pico_usb_serial.rs
- boards/pro_micro_rp2040/examples/pro_micro_rainbow.rs
- rp2040-hal/src/timer.rs
> Adds Reset for Timer

- boards/feather_rp2040/Cargo.toml
- boards/feather_rp2040/README.md
- boards/feather_rp2040/examples/feather_neopixel_rainbow.rs
This uses PIO to drive the NeoPixel just like the Pro Micro example does.
> Add an example using the Feather RP2040's onboard NeoPixel

- rp2040-hal/src/pio.rs
Start to address #186.
#177 added the Send trait to StateMachine, Tx and Rx, That documentation was expanded as suggested. 
PIO, UninitStateMachine, Interrupt were marked Send before #177, added some documentation to those as well.
> Document properties needed for PIO Send safety

- rp2040-hal/src/multicore.rs
Fixes: https://github.com/rp-rs/rp-hal/issues/218
theoretically we could return an `Err` if the slice isn't fully aligned. should we?
> use user-provided stack for core 1

- rp2040-hal/examples/multicore_fifo_blink.rs
- rp2040-hal/src/multicore.rs
> Add basic multicore FIFO example

- boards/rp-pico/Cargo.toml
- boards/rp-pico/examples/pico_ws2812_led.rs
Here is the example for WS2812 LED, like the other example tested with hardware of course, with comments and ASCII diagram :-)
> Add Raspberry Pi Pico WS2812 LED example

- rp2040-hal/src/timer.rs
Hi!
Mathias on the rp-rs Matrix channel remarked that there is a race condition in the schedule() function for Timer alarms: 
(Please excuse my humor :-) )
I wrapped the critical section in a `cortex_m::interrupt::free(|_| { })`. Mathias said that it would be better for hard real time to add a check instead, whether the alarm time was already reached. But then figured that it would be quite hard to actually trigger the (right) alarm interrupt from there afterwards.
So using `interrupt::free` seems to be the best solution for now and gets rid of the race condition.
> Fix alarm schedule race condition

- README.md
> Add missing Solder Party Stamp to top README

- rp2040-hal/src/uart/utils.rs
> Added `impl Default` for UartConfig

- rp2040-hal/src/i2c/peripheral.rs
The `start_det` flag is set as soon as a start condition occurs whereas `rd_req` flag is only set once the address byte is received.
> Fix i2c peripheral mode state machine

- rp2040-hal/src/watchdog.rs
Initial work to get watchdog working properly.
Need to work out what is sufficient.
Currently using the same flags from the [pico bootrom](https://github.com/raspberrypi/pico-bootrom/blob/7a751f28436a8ee4849ac7799eb3aa1457e6f091/usb_device_tiny/runtime.c#L70)
> Set hw reset bits for watchdog

- rp2040-hal/examples/gpio_irq_example.rs
Add a GPIO interrupt example to the HAL
This was intended to be much more trivial, but it's hard to be simple, clear and safe at the same time.
Since this is intended to be the easiest guide to interrupts, please be critical of any complexity that might trip up beginners.
And if you are a beginner and you are reading this - your feedback is also very welcome, please comment!
Closes #275
> Add GPIO interrupt example

- rp2040-hal/src/usb.rs
Just applied the code changes suggested by clippy.
> Fix clippy warnings

- rp2040-hal/CHANGELOG.md
Getting change log up-to-date so we can think about making a new release
> Add changes since 0.3.0 to changelog

- boards/rp-pico/examples/pico_rtic.rs
- rp2040-hal/src/timer.rs
Allows for writing more reusable code :)
> Abstract alarms

- boards/rp-pico/README.md
- boards/rp-pico/examples/pico_pwm_servo.rs
> Add Pico PWM micro servo example

- rp2040-hal/src/pio.rs
Make PIO installed program offset accessible with an accessor method
#354
> accessor for offset of installed program on pio

- boards/arduino_nano_connect/Cargo.toml
- boards/pimoroni-pico-lipo-16mb/Cargo.toml
- boards/rp-pico/Cargo.toml
Also remove dependency in two places where it is not used
> Update dev-dependency on cortex-m-rtic to 1.1.2

- README.md
- boards/pimoroni-pico-explorer/src/lib.rs
- rp2040-hal/src/timer.rs
Some small improvements found when using the explorer base bsp
> Explore base improvements

- rp2040-hal/src/gpio/pin.rs
> Add bsp_pin example

- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
- rp2040-hal/src/adc.rs
- rp2040-hal/src/pio.rs
Doc comment of rx.is_empty() was wrong, and rx.is_full() was missing.
> Fix PIO rx fifo status

- boards/rp-pico/Cargo.toml
- boards/rp-pico/examples/pico_pio_pwm.rs
- boards/rp-pico/examples/pwm.pio
This adds a more advance pio example which uses side set and instruction injection
> Add pio pwm example

- boards/adafruit-macropad/src/lib.rs
Cherry-picked this fix from #340
> Fix pin number for speaker in adafruit macropad bsp

- README.md
Added new lines for consistency on readme and removed ghost empty space
> Formatting Readme

- rp2040-hal/src/timer.rs
> Add docs and doc-example for Timer

- rp2040-hal/src/pwm/mod.rs
> Fix handling of duty cycle while PWM channels is disabled

- rp2040-hal/src/pwm/mod.rs
> Implement NonPwmPinMode for gpio::Disabled

- .github/workflows/build_and_test.yml
- boards/rp-pico/CHANGELOG.md
- boards/rp-pico/Cargo.toml
- boards/rp-pico/examples/pico_usb_serial.rs
- boards/rp-pico/examples/pico_usb_twitchy_mouse.rs
- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/src/usb.rs
- rp2040-hal/src/usb/errata5.rs
This is PR presents a first attempt at implementing RP2040-E5.
It still lacks a way to force the init of the timer. Any suggestion is welcome.
I don't have a way to replicate the issue so I can't check if the implementation is correct.
Anyone able to replicate the issue is invited to test it and let me know of the result :)
> Implements USB enumeration workaround (RP2040-E5).

- rp2040-hal/src/gpio/dynpin.rs
This is a quality of life type of change.
> Add Debug and defmt::Format to the public types of rp2040_hal::gpio::dynpin

- rp2040-hal/src/watchdog.rs
> Check watchdog load value max value before multiplying by 2, to avoid integer overflow

- boards/rp-pico/examples/pico_i2c_pio.rs
- boards/rp-pico/examples/pico_uart_irq_buffer.rs
- boards/rp-pico/examples/pico_uart_irq_echo.rs
- rp2040-hal/CHANGELOG.md
- rp2040-hal/examples/adc.rs
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/examples/uart.rs
- rp2040-hal/src/uart/mod.rs
- rp2040-hal/src/uart/utils.rs
The change of the baudrate type is up for discussion, if it's controversial, I'll roll it back.
> Implement UartConfig::new constructor method

- rp2040-hal/examples/pio_synchronized.rs
> Use InstalledProgram::share() in examples/pio_synchronized.rs

- boards/pimoroni-pico-explorer/src/lib.rs
- boards/rp-pico/examples/pico_rtic_monotonic.rs
- rp2040-hal/src/pio.rs
- rp2040-hal/src/sio.rs
- rp2040-hal/src/spi.rs
- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/usb.rs
(One warning was just silenced because I consider the current code more readable)
> Fix some clippy warnings flagged by current beta

- boards/arduino_nano_connect/src/lib.rs
> Use generic boot loader for arduino nano connect

- rp2040-hal/src/gpio/dynpin.rs
Added functions to interact with interrupts to DynPin.
It's a copy of the same functions found in Pin.
Resolves #476
> Dynpin interrupts

- rp2040-hal/src/timer.rs
**Issue**
#522
In current scenario there is no way to disable a triggered alarm. The only choice is to cancel the timer but it also disables other ongoing alarms. This has a negative effect if the alarm is used for detection of timeouts and should be cancelled if the current state changes.
Scheduling alarm for zero is out of option as it's simply rejected. And it wouldn't look good for readability.
**Solution**
I've added `cancel` method to the `Alarm` trait. This way only the related alarm could be cancelled without effecting other alarms and the timer.
> Added Alarm cancellation feature.

- .github/workflows/build_and_test.yml
requires https://github.com/rp-rs/rp-hal/pull/487 first
> Amend CI to build rp2040-hal without the bsp's features.

- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
> Prepare release of version 0.8.0

- rp2040-hal/CHANGELOG.md
Trying something new here: Adding the PR's reference to the entry.
> update changelog in preparation of 0.8.1

- rp2040-hal/src/multicore.rs
See these embassy PR for more explanation:
- https://github.com/embassy-rs/embassy/pull/1459
- https://github.com/embassy-rs/embassy/pull/1460
> multicore: Fix undefined behaviour in multicore

- .github/workflows/build_and_test.yml
- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
> Bump MSRV to 1.64

- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
This already mentions #621 in the CHANGELOG, so it should be merged after that PR.
> Prepare release 0.9.0

- README.md
> Enable common features in example build command

- rp2040-hal-examples/src/bin/pio_side_set.rs
- rp2040-hal/src/arch.rs
- rp2040-hal/src/lib.rs
This improves code portability between rp2040-hal and rp235x-hal
> Provide arch module on RP2040

- rp235x-hal/src/gpio/func.rs
- rp235x-hal/src/gpio/mod.rs
- rp235x-hal/src/gpio/pin.rs
- rp235x-hal/src/gpio/pull.rs
- rp235x-hal/src/sio.rs
This is a port of #861 to rp235x-hal
> implement Debug support for the GPIO structures (RP235x)

- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/writer.rs
- rp235x-hal/src/uart/peripheral.rs
- rp235x-hal/src/uart/writer.rs
> Fix implementations of embedded_io::Write for UartPeripheral

- on-target-tests/tests/multicore.rs
- rp235x-hal/src/arch.rs
- rp235x-hal/src/multicore.rs
> Enable co-processors when spawning on core1

- rp235x-hal/src/dma/mod.rs
I forgot to update this comment in my DMA pull request.
> Update DMA documentation

- rp235x-hal-examples/src/bin/pio_blink_pio2.rs
- rp235x-hal/src/pio.rs
- rp235x-hal/src/resets.rs
Tested on an Raspberry Pi Pico 2.
> Add support for PIO2

- rp235x-hal/src/pio.rs
Some more changes which add PIO2 support.
> More PIO2 stuff
