- .cargo/config
Add `.cargo/config` defining the build target so that you can build with simply `cargo build`.
> Add .cargo/config defining the build target

- rp2040-hal/src/rom_data.rs
It seems like the rom_table_lookup missed one level of
pointer dereferencing.
After comparing it to the working call to reset_usb_boot() in
https://github.com/jannic/rp-microcontroller-rs/blob/master/util/rp2040-panic-usb-boot/src/lib.rs,
I changed the code until it generated basically the same assembly.
With that change, I was able to successfully call rom_data::reset_to_usb_boot()
I still don't like the type RomTableLookupFn, which just returns
some generic T without any checks, and I think rom_table_lookup
should be unsafe. But as none of those are pub, it doesn't matter too
much. So I just made the changes necessary to make the code work.
> fix rom_table_lookup

- .github/workflows/check.yml
- rp2040-hal/src/rom_data.rs
Besides the normal usage of unit-tests this also ensures that
example in doc-comments do at least compile.
This expands #23
> Add `cargo test` to CI run and fix an error found by it

- .github/workflows/check.yml
- .github/workflows/clippy.yml
- .github/workflows/rustfmt.yml
- .github/workflows/tests_host.yml
- rp2040-hal/src/xosc.rs
When trying to merge the UART branch the "cargo test" step was breaking the CI workflow.
CI didn't give any easy feedback as to what was broken.
This PR moves all different CI steps into their own workflow like some other HALs do, so that we can tell what the error is based on which workflow failed. This also means the tests can run in parallel which should improve run times.
I have moved the "cargo test" step in the tests_host.yml file but commented it out.
I will raise an issue to discuss whether we can fix it or we should remove it.
> CI improvement: separate tasks, disable cargo test, fix clippy warning

- rp2040-hal/src/gpio.rs
- rp2040-hal/src/lib.rs
- rp2040-hal/src/pll.rs
- rp2040-hal/src/resets.rs
- rp2040-hal/src/uart.rs
Currently, `pll` and `uart` do not bring the module out of reset before attempting to use it.
If the module is still in reset, you cannot use it.
This PR brings the UART and PLL out of reset before attempting to use them.
> Have the `pll` and `uart` HAL modules bring the hardware out of reset

- rp2040-hal/src/sio.rs
A simple working implementation of hardware divide/modulo, tested on hardware.
I don't have much experience (both embedded and Rust) so there are a bunch of questions I want to ask:
* In the `sio.rs` module, there are comment that say:
```rust
// we can hand out other things here, for example:
// gpio_qspi
// divider
// interp0
// interp1
```
but I could not figure out how to fit my divmod implementation in there.
* For this initial implementation I split it into two different structs for unsigned and signed divmod operations. Is it possible to define a more generic implementation? I thought about using the trait bound `impl Into<u32>` or `impl Into<i32>` but both doesn't capture everything.
* I shamelessly copied the `sio()` function from the module `gpio.rs`. However, I'm not so sure …
> Hardware divide/modulo support

- rp2040-hal/src/watchdog.rs
I have limited experience in this space (both embedded and rust) so I was hoping to iterate on the design and implementation of this from feedback.
I'm aware of two things that may drive design (not to say there aren't more):
* Tick generation should be enabled prior to enabling the watchdog
* RP2040-E1
In regards to RP2040-E1, should we restrict the counter to the maximum load value (0xFFFFFF / 2) and if so, how?
> Watchdog implementation

- boards/feather_rp2040/Cargo.toml
- boards/pico/Cargo.toml
- boards/pico_explorer/Cargo.toml
- boards/pico_lipo_16mb/Cargo.toml
- rp2040-hal/Cargo.toml
For the HAL, currently just passes the feature to the PAC.
Also pass the 'rt' feature through to the HAL for all the BSP crates.
This is needed to make using interrupts easier (feature use is global in Cargo, so if you include the PAC as a dependency in your application with the 'rt' feature, that will pollute the dependency inside the HAL -- but we probably shouldn't rely on that)
And either way, BSPs (should) re-export the HAL (as `bsp::hal`), and the HAL re-exports the PAC (as `hal::pac`) -- so there should be no reason to actually directly depend on the PAC (or the HAL if you are using a BSP)
> Add 'rt' feature [for the HAL to pass to the PAC]

- rp2040-hal/examples/pwm_blink.rs
- rp2040-hal/src/pwm.rs
Ran pwm.rs and examples/pwm_blink.rs through cargo-fmt to keep CI happy.
No functional changes.
> Formatting fixes for pwm + example

- .github/workflows/check.yml
- .github/workflows/clippy.yml
- .github/workflows/rustfmt.yml
- .github/workflows/tests_host.yml
- rp2040-hal/src/lib.rs
I have moved the deny warnings error to ci instead of every build.
See https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deny-warnings.md for a rationale.
> Deny warnings in ci

- rp2040-hal/src/clocks/macros.rs
- rp2040-hal/src/pwm.rs
The newer version of svd2rust marks write_with_zero calls as unsafe, where the old one did not.
This PR wraps the only 2 calls instances of this in the HAL with unsafe blocks to fix the compile errors.
> Add unsafe blocks around write_with_zero calls

- rp2040-hal/src/sio.rs
There was a mistake when I copy pasted the code in #40. My apologies.
> Fix unsigned hardware divide/modulo

- .cargo/config
- README.md
It might even be a good idea to set the runner in de committed cargo config. But I am not sure if that interferes with debugging using a probe etc..
> Simplify uf2 flashing

- CHANGELOG.md
- rp2040-hal/examples/watchdog.rs
- rp2040-hal/src/watchdog.rs
Add a standalone example and a doc-example showing how to use the Watchdog peripheral driver.
Resolves #85
> Watchdog example

- Cargo.toml
- boards/feather_rp2040/Cargo.toml
- boards/feather_rp2040/README.md
- boards/feather_rp2040/examples/feather_blinky.rs
- boards/feather_rp2040/src/lib.rs
Added a blinky example for the Adafruit Feather RP2040 board which uses the flash support added in rp-rs/rp2040-boot2-rs#9 . The example is based on the Pico board example with modifications to utilize the board support crate for the Feather RP2040 board. The Cargo.toml references the specific version rp-rs/rp2040-boot2-rs#9 , this should be changed once we have a new release for rp2040-boot2-rs.
> Adafruit feather rp2040

- .gitignore
- boards/adafruit_macropad/Cargo.toml
- boards/adafruit_macropad/README.md
- boards/pico_explorer/README.md
- boards/pico_lipo_16mb/README.md
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
The READMEs that go to crates.io need to be in the crate dir
Improves  #81 
Closes #42
> Update and move readmes

- rp2040-hal/src/i2c.rs
When doing an i2c WriteRead the driver would lock up indefinitely due to an error in how the transmit FIFO was being checked.
I also removed asserts for zero length read and writes, since it's quite legal for someone to do a zero length write to check for the existence of a peripheral on the bus, and some devices do not have any registers, so they do not require writes in WriteRead.
Also improves error handling.
Fixes #95
> i2c lockup fix

- boards/pico/Cargo.toml
- boards/pico/examples/pico_usb_serial.rs
- rp2040-hal/Cargo.toml
- rp2040-hal/src/usb.rs
This PR depends on https://github.com/rp-rs/rp2040-pac/pull/36 in order to dramatically simplify the driver's implementation. See the PR's description for details.
It has been tested on a pi pico board with the demo application features in this PR.
- RP2040-E5 (Device enumeration workaround) is not implemented
- Suspend/resume is not implemented
- VBus detection is not tested and may not be fully implemented
> Implement usb_device for rp2040

- boards/pico/examples/pico_usb_serial_interrupt.rs
The existing USB example is polled in the main loop - this one is polled from within the USB interrupt instead.
An RTIC-based example would be even better, but this is a good step towards that.
> Add interrupt-driven USB example

- boards/pico/Cargo.toml
- boards/pico/examples/pico_usb_twitchy_mouse.rs
I did a port of https://github.com/atsamd-rs/atsamd/blob/master/boards/itsybitsy_m0/examples/twitching_usb_mouse.rs to the Pico.
Requires #104 to work, as the control endpoint it uses has a buffer length < 64 bytes.
> Add port of usb-twitchy-mouse

- boards/pico/Cargo.toml
- boards/pico/examples/pico_rtic.rs
Created RTIC example that blinks gpio25 at an interval of 1 second from a interrupt with the RTIC framework. Uses local and shared data from RTIC with pac access through the RTIC Mutex.
I couldn't get RTIC 0.5.x working as the `Nr` trait was needed where as 0.6.x uses `InterruptNumber`
Happy to fix any suggestions!
Resolves #108
> Add Pico RTIC Timer Blinky Example

- rp2040-hal/Cargo.toml
- rp2040-hal/src/lib.rs
- rp2040-hal/src/pio.rs
Add support for PIO hardware. This PR is based on #9 and implements most of the missing features, including interrupts.
This PR depends on [`pio-rs#3`](https://github.com/rp-rs/pio-rs/pull/3).
Closes #5.
> PIO support

- rp2040-hal/src/spi.rs
Fixed bug where a postdiv of 256 would not be represented as a u8 resulting in a panic on subtraction underflow
> Fixed u8 overflow in spi with large postdiv

- boards/pico/Cargo.toml
- boards/pico/examples/pico_countdown_blinky.rs
- rp2040-hal/src/timer.rs
This PR implements support for the [`embedded_hal::timer`](https://docs.rs/embedded-hal/0.2.6/embedded_hal/timer/index.html) traits.
> Add embedded_hal::timer support

- boards/pico/examples/pico_usb_serial_interrupt.rs
- boards/pico/examples/pico_usb_twitchy_mouse.rs
- rp2040-hal/src/usb.rs
Move enabling of buff_status, buff_reset and setup_req into UsbBus::enable() and clear the flags from within the UsbBus::poll() so that user code doesn't need to touch the registers.
This way you can either manually poll from within a forever loop, or you can unmask the interrupt and call poll from within the USBCTRL_IRQ.
I've updated the interrupt examples to use the latter, as a reference for how much simpler this is.
I also moved the setup_req portion of the poll handler higher up so that will happen even in the presence of a reset request. This matches the behaviour of the driver in the C USB library that the official SDK uses.
> Handle usb interrupt flags in driver

- boards/pico/examples/pico_usb_serial.rs
- boards/pico/examples/pico_usb_serial_interrupt.rs
- rp2040-hal/src/usb.rs
Prevents `DataIn` of the previous request from being sent to the host when a new setup is received.
> Work around enumeration issues with small ep0 max packet size.

- rp2040-hal/src/gpio/mod.rs
- rp2040-hal/src/gpio/pin.rs
- rp2040-hal/src/gpio/reg.rs
Interrupt status, input, output enable and output can be overridden. See documentation for GPIO0_CTRL for more info.
As a background, I happen to need input inversion as my optocoupler inverts the signal and I don't want to modify my existing PIO code.
> Implement GPIO override

- rp2040-hal/src/spi.rs
When using the library embedded-sdmmc i needed a way to reset the clock of the spi peripheral without having ownership of the spi device. This is the way i came up with.
Note: The diff looks kind of weird the new function has not moved but the set_baudrate and set_format functions has moved to be available internally both in enabled and disabled state.
Example usage code can be found here:
https://github.com/JoNil/pico_plant/blob/fc872a3b145f54c2835442413a1a1673e1803d01/src/main.rs#L208
> Made spi set_baudrate public

- CHANGELOG.md
- boards/adafruit_macropad/Cargo.toml
- boards/feather_rp2040/Cargo.toml
- boards/pico/Cargo.toml
- boards/pico_explorer/Cargo.toml
- boards/pico_lipo_16mb/Cargo.toml
- boards/pro_micro_rp2040/Cargo.toml
- rp2040-hal/Cargo.toml
It's been a bit more than a month, I think we're due for a release.
Lots of new code + docs and it would be nice for it to be on crates.io and docs.rs
> Update changelog and bump verson for hal release 0.3.0

- boards/pico/Cargo.toml
- boards/pico/examples/pico_usb_twitchy_mouse.rs
usbd-hid 0.5.1 contained an accidental semver breaking change
fix example accordingly
> fix pico_usb_twitchy_mouse with usbd-hid >= 0.5.1

- CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/src/rosc.rs
Implement [`rand_core::RngCore`](https://docs.rs/rand_core/0.6.3/rand_core/trait.RngCore.html) for `RingOscillator` from the `get_random_bit` function. This is not suitable for security purposes so [`rand_core::CryptoRng`](https://docs.rs/rand_core/0.6.3/rand_core/trait.CryptoRng.html) has not been implemented.
> Implement RngCore for RingOscillator

- rp2040-hal/src/gpio/dynpin.rs
- rp2040-hal/src/gpio/pin.rs
- rp2040-hal/src/gpio/reg.rs
When both pull-up and pull-down are enabled, the RP2040 enters a
so-called "bus keep" function, which uses a weak pull to tue current
high/low state of the GPIO.
See for example
https://raspberrypi.github.io/pico-sdk-doxygen/group__hardware__gpio.html#gab6bf9552da32b3dd0a5d0db45d8374fc
As this change adds new variants to public enums, it is a semver breaking change and therefore needs an appropriate version increment, when merged.
> Implement bus keep inputs, as documented in C SDK

- .github/workflows/check.yml
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
- rp2040-hal/src/adc.rs
- rp2040-hal/src/gpio/dynpin.rs
- rp2040-hal/src/gpio/pin.rs
- rp2040-hal/src/i2c.rs
- rp2040-hal/src/pwm/mod.rs
- rp2040-hal/src/spi.rs
- rp2040-hal/src/timer.rs
- rp2040-hal/src/uart.rs
- rp2040-hal/src/watchdog.rs
With this change, it is possible to use rp2040-hal with embedded-hal 1.0.0-alpha.5.
The new trait implementations are hidden behind a feature flag, `eh1_0_alpha`, to avoid semver breaking changes as long as that flag is not set.
When using that flag, breaking changes can be expected, as embedded-hal 1.0 is not yet released. This is documented in README.md.
When embedded-hal 1.0 is released, we have several options:
- We could activate it unconditionally (and just remove the feature flag).
- We could rename the feature flag to `eh1_0` or similar.
- We could hide support for embedded-hal 0.2 behind a feature flag and support 1.0 by default.
- We could remove support for embedded-hal 0.2 and replace it with support for version 1.0.
Currently I'd prefer the first option, as long as support …
> implement embedded-hal 1.0.0-alpha.5

- boards/feather_rp2040/examples/feather_neopixel_rainbow.rs
The signature for Timer::new() changed in #136 to require passing resets, this PR was created before that was merged.
Updated the call to Timer::new() to match all the other examples.
> Update example feather_neopixel_rainbow.rs for new Timer syntax

- CHANGELOG.md
- Cargo.toml
- rp2040-hal/Cargo.toml
- rp2040-hal/examples/pio_blink.rs
- rp2040-hal/examples/pio_proc_blink.rs
- rp2040-hal/src/pio.rs
- rp2040-hal/src/prelude.rs
The current PIO API has a number of limitations:
- As the state machines are contained in `PIO`, they cannot be moved around individually. Sometimes, a single PIO block implements multiple functions that are used in completely different parts of the code base.
- `StateMachine` is not Send, although it could be.
- Multiple state machines should be able to share code to reduce instruction space usage, yet currently they are not because PIOBuilder always allocates space. Sometimes, multiple state machines implement the same functionality (e.g., multiple SPI or I2C buses).
- Some functions must only be called in specific configurations. For example, pin directions have to be set while the state machine is stopped, as PINCTRL is modified. The current API does not reflect such restrictions, …
> Rework the PIO API

- Cargo.toml
- README.md
- boards/qt_py_rp2040/Cargo.toml
- boards/qt_py_rp2040/README.md
- boards/qt_py_rp2040/examples/qt_py_rainbow.rs
- boards/qt_py_rp2040/src/lib.rs
This PR implements a BSP for the Adafruit QT Py RP2040 found [here](https://www.adafruit.com/product/4900).
Neopixel example has been tested and is working on actual hardware.
Pin mappings were taken from Adafruit's CircuitPython repo and can be found [here](https://github.com/adafruit/circuitpython/blob/main/ports/raspberrypi/boards/adafruit_qtpy_rp2040/pins.c).
> Implement QT Py BSP with example

- rp2040-hal/src/i2c.rs
Fixed i2c write_read function. Without that fix, reading an mpu6050 (using https://crates.io/crates/mpu6050) resulted in erratic values.
> Fix i2c write read

- Cargo.toml
- boards/feather_rp2040/examples/feather_neopixel_rainbow.rs
- boards/pro_micro_rp2040/examples/pro_micro_rainbow.rs
- boards/qt_py_rp2040/examples/qt_py_rainbow.rs
PIO's API has had a breaking change in its API that required WS2812 to update its own API.
This PR applies the required changes.
Related changes:
* https://github.com/rp-rs/rp-hal/pull/143
* https://github.com/ithinuel/ws2812-pio-rs/pull/2
> Update WS2812 usage after PIO api's breaking change.

- rp2040-hal/Cargo.toml
It's only used in an example, so it doesn't need to be a regular
dependency.
> Make pio-proc a dev-dependency

- rp2040-hal/src/gpio/mod.rs
- rp2040-hal/src/gpio/pin.rs
- rp2040-hal/src/gpio/reg.rs
Both #4 and #24 left interrupts for GPIO as todos.
Adds the following methods for each PIN:
- `clear_interrupt(interrupt: Interrupt)`
- `interrupt_status(interrupt: Interrupt) -> bool`
- `is_interrupt_enabled(interrupt: Interrupt) -> bool`
- `set_interrupt_enabled(interrupt: Interrupt, enabled: bool)`
- `is_interrupt_forced(interrupt: Interrupt) -> bool`
- `set_interrupt_forced(interrupt: Interrupt, forced: bool)`
> GPIO interrupt

- rp2040-hal/src/spi.rs
This allows you to use a 62.5 MHz SPI baud rate assuming the default 125
MHz peripheral clock. It would previously crash due to a division by
zero.
> spi: support zero post-divide

- rp2040-hal/src/uart.rs
Set uartlcr_h before enabling the UART.
Writing uartlcr_h while the UART is enabled is forbidden by the datasheet.
Details can be found here:
https://developer.arm.com/documentation/ddi0183/g/programmers-model/register-descriptions/line-control-register--uartlcr-h?lang=en
(As referenced from the Datasheet)
> Fix UART init code

- rp2040-hal/src/uart.rs
The return type of `read_raw` was changed so that it conforms to the std::io::Read trait. This also fixes a bug in the `read_full_blocking` code.
> Change UART raw read return type and fix full read

- boards/pico/Cargo.toml
- boards/pico/examples/pico_i2c_controller_peripheral/controller.rs
- boards/pico/examples/pico_i2c_controller_peripheral/main.rs
- boards/pico/examples/pico_i2c_controller_peripheral/peripheral.rs
- rp2040-hal/Cargo.toml
- rp2040-hal/src/i2c.rs
- rp2040-hal/src/i2c/controller.rs
- rp2040-hal/src/i2c/controller/embassy_support.rs
- rp2040-hal/src/i2c/peripheral.rs
- rp2040-hal/src/lib.rs
The PR features:
* an implementation for asynchronous API for I2C as bus controller
* an implementation for asynchronous API for I2C as bus peripheral
* an advanced example that shows the use of read/write for both controller & peripheral.
Open questions:
* Is `nostd_async` an appropriate executor? (it only works on stable toolchain)
* Shall the peripheral side of the demo validate the state transition (as implemented) or simply serve the requests?
* Shall we implement the `embassy-trait` for i2c? The proposed API & the embassy APIs are basically async adaptation of the eh's blocking hal.
> Implement peripheral support for i2c and an advanced example

- rp2040-hal/src/gpio/pin.rs
This allows the `FuncionPio?` to be inferred from the `pac::PIO?` used.
This change shall be transparent for anyone using the `FunctionPio?` aliases.
> Use the PIOn peripherals in pin functions rather than creating an enum.

- boards/feather_rp2040/Cargo.toml
- boards/itsy_bitsy_rp2040/Cargo.toml
- boards/pro_micro_rp2040/Cargo.toml
- boards/qt_py_rp2040/Cargo.toml
This will help future update of the driver without breaking rp-hal's main branch.
The expected flow would then be:
* Update rp-hal/rp2040-hal with new API & deprecation of the current API
* Update the affected dependencies (ws2812-pio/i2c-pio)
* Update the examples using those dependencies & bump the pinned revs
* Remove deprecated API when deemed appropriate for the community
A short term example will be easing the integration of:
- https://github.com/rp-rs/rp-hal/pull/193
- https://github.com/ithinuel/i2c-pio-rs/pull/1
- https://github.com/ithinuel/ws2812-pio-rs/pull/4
> pin ws2812-pio to a specific sha

- README.md
I skipped ahead in the instructions, running the other `cargo install elf2uf2-rs` that wasn't fixed in #173, and encountered the same issue.
> Add --locked to second `cargo install elf2uf2-rs`

- boards/feather_rp2040/Cargo.toml
- boards/feather_rp2040/examples/feather_neopixel_rainbow.rs
- boards/itsy_bitsy_rp2040/Cargo.toml
- boards/itsy_bitsy_rp2040/examples/itsy_bitsy_rainbow.rs
- boards/pro_micro_rp2040/Cargo.toml
- boards/pro_micro_rp2040/examples/pro_micro_rainbow.rs
- boards/qt_py_rp2040/Cargo.toml
- boards/qt_py_rp2040/examples/qt_py_rainbow.rs
This change makes the ws2812 driver take ownership of the pin rather than its id.
This strengthen the relation between the LED driver and the pin used as well as simplifying it integration by letting the compiler resolve the pin id from the pin instance.
> Bump to latest ws2812 driver's revision.

- rp2040-hal/Cargo.toml
- rp2040-hal/src/i2c.rs
- rp2040-hal/src/i2c/controller.rs
- rp2040-hal/src/spi.rs
- rp2040-hal/src/uart.rs
Only compile-tested. But we all know, once rust code compiles, it works.
> Update eh1_0_alpha feature for embedded-hal 1.0.0-alpha.6

- rp2040-hal/src/timer.rs
This PR adds an API for the 4 build-in alarms.
To schedule an alarm:
```rust
let mut timer = Timer::new(cx.device.TIMER, &mut cx.device.RESETS);
let mut alarm0 = timer.alarm_0().unwrap();
alarm0.enable_interrupt();
alarm0.schedule(300_000.microseconds()).unwrap();
// interrupt
#[no_mangle]
pub fn TIMER_IRQ_0() {
alarm0.clear_interrupt();
led.toggle().unwrap();
alarm0.schedule(300_000.microseconds()).unwrap();
}
```
Closes #100
> Added timer alarms

- rp2040-hal/src/sio.rs
Implements spinlocks, a simple wrapper around the sio::spinlockX address.
As per documentation:
```
2.3.1.3. Hardware Spinlocks
The  SIO  provides  32  hardware  spinlocks,  which  can  be  used  to  manage  mutually-exclusive  access  to  shared  software
resources. Each spinlock is a one-bit flag, mapped to a different address (from SPINLOCK0 to SPINLOCK31). Software
interacts with each spinlock with one of the following operations:
• Read: attempt to claim the lock. Read value is nonzero if the lock was successfully claimed, or zero if the lock had
already been claimed by a previous read.
• Write (any value): release the lock. The next attempt to claim the lock will be successful.
If both cores try to claim the same lock on the same clock cycle, core 0 succeeds.
Generally  software …
```
> Added spinlocks

- rp2040-hal/src/pio.rs
This is meant to make the action caused by the function call more obvious. (Better suggestions are welcome!)
set_instruction sounds a little bit like it would somehow change the instruction memory of the state machine, which is not the case. All it does is forcing the state machine to immediately execute the specified instruction.
Also, update the comment regarding calling this function while the state machine is running with information from datasheet section 3.5.7.
@ithinuel, if this is merged, i2c-pio-rs needs to be updated as well, as it calls set_instruction.
> Rename set_instruction to exec_instruction

- boards/pico/examples/pico_usb_serial.rs
> pico_usb_serial: Handle errors of serial.write()

- .github/workflows/check.yml
- rp2040-hal/Cargo.toml
- rp2040-hal/src/rtc.rs
- rp2040-hal/src/rtc/datetime_chrono.rs
- rp2040-hal/src/rtc/datetime_no_deps.rs
- rp2040-hal/src/rtc/filter.rs
- rp2040-hal/src/rtc/mod.rs
Decided to rewrite this code from scratch because I wanted to set it up better.
Continuation of #207 
Added a new struct `RealTimeClock` that allows programmers to set and get the time of the rp2040, as per chapter 4.8 of the datasheet. Also added the ability to set an alarm. 
This code is mostly ported from the C sdk, except that I split `DateTime` into `DateTime` and `DateTimeFilter`, so we don't have to deal with the -1 logic that the C sdk has.
With the `chrono` feature enabled, `DateTime` and `DayOfWeek` are aliases of `chrono::NaiveDateTime` and `chrono::Weekday` instead, so we have all the chrono functionality. I've added a test pipeline step for this.
> Added RtcClock DateTime and alarms

- rp2040-hal/src/gpio/reg.rs
- rp2040-hal/src/pwm/reg.rs
Rust 1.57 clippy triggers warnings that were not present on 1.56, breaking CI
```
warning: docs for unsafe trait missing `# Safety` section
```
Since we borrowed these traits from atsamd-rs's pin abstraction, I've copied the safety docs from there.
https://github.com/atsamd-rs/atsamd/blob/16ff6e0afd3e5e01084149ad033ac04f5eb9fd82/hal/src/gpio/v2/reg.rs#L213
> Add safety docs from atsamd-rs to GPIO traits to make CI happy

- rp2040-hal/src/sio.rs
Generate a send event signal via `sev` in sio.fifo.write() so that sio.fifo.blocking_read() will wake up.
Closes #222
> Generate sev in sio.fifo.write()

- boards/pico/examples/pico_i2c_pio.rs
- rp2040-hal/examples/adc.rs
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/examples/uart.rs
- rp2040-hal/src/uart.rs
For communicating with an [CH9121](https://www.waveshare.com/wiki/Pico-ETH-CH9121) Ethernet/serial adapter, I need to be able to change the bit rate of an existing UART, as the chip uses the same serial line for both configuration and data transfer, but with different bit rates.
The existing UartPeripheral doesn't allow that. And as the current `disable()` method looks rather useless, as it's not possible to `enable()` an UART after disabling it, I think it would be better to make the API a little bit more symmetrical, so one can do:
```
let disabled_uart = hal::uart::UartPeripheral::<_, _>::new(pac.UART0, &mut pac.RESETS);
let enabled_uart = disabled_uart.enable(config, frequency).unwrap();
let disabled_uart = enabled_uart.disable();
let enabled_uart = disabled_uart.enable(other_config, …
```
> Refactor uart init

- boards/pico/Cargo.toml
- rp2040-hal/Cargo.toml
Newer nightly's of the compiler now detect a missing bound on some embassy traits.
Bump embassy related dependencies to benefit from the fixes.
> Bump embassy's dependencies

- boards/pico/Cargo.toml
- boards/pico/examples/pico_rtic.rs
Example now uses pico bsp, RTIC multilock, and rp-hal Timer Alarm HAL.
> Update Pico RTIC example to use timer alarm HAL

- rp2040-hal/src/uart.rs
Otherwise it's impossible to have a configuration which differs from the provided default options.
> Make fields in UartConfig public

- rp2040-hal/Cargo.toml
The git dep prevents us from publishing, rp2040-hal, and embassy
aren't doing a release any time soon.
> Comment out embassy traits.

- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
Somehow we already had a bunch of commits talking about 0.3.0, but it
was never released. Hence why this maybe doesn't change as many version
numbers as you might expect.
> Set up for 0.3.0 release.

- boards/rp-pico/examples/pico_i2c_pio.rs
- rp2040-hal/examples/adc.rs
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/examples/uart.rs
- rp2040-hal/src/uart/common_configs.rs
- rp2040-hal/src/uart/mod.rs
- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/pins.rs
- rp2040-hal/src/uart/reader.rs
- rp2040-hal/src/uart/utils.rs
- rp2040-hal/src/uart/writer.rs
This PR makes the UartPeripheral take ownership of the pins that it needs.
```rust
const XOSC_CRYSTAL_FREQ: u32 = 12_000_000; // Typically found in BSP crates
let mut peripherals = pac::Peripherals::take().unwrap();
let sio = Sio::new(peripherals.SIO);
let pins = Pins::new(peripherals.IO_BANK0, peripherals.PADS_BANK0, sio.gpio_bank0, &mut peripherals.RESETS);
let mut watchdog = Watchdog::new(peripherals.WATCHDOG);
let mut clocks = init_clocks_and_plls(XOSC_CRYSTAL_FREQ, peripherals.XOSC, peripherals.CLOCKS, peripherals.PLL_SYS, peripherals.PLL_USB, &mut peripherals.RESETS, &mut watchdog).ok().unwrap();
// This is new:
// Set up UART on GP0 and GP1 (Pico pins 1 and 2)
let pins = (
pins.gpio0.into_mode::<FunctionUart>(),
pins.gpio1.into_mode::<FunctionUart>(),
);
let uart = …
```
> UART owned pins + reader/writer split

- boards/adafruit-feather-rp2040/src/lib.rs
- boards/adafruit-itsy-bitsy-rp2040/src/lib.rs
- boards/adafruit-kb2040/examples/adafruit_kb2040_rainbow.rs
- boards/adafruit-macropad/src/lib.rs
- boards/adafruit-qt-py-rp2040/src/lib.rs
- boards/pimoroni-pico-explorer/src/lib.rs
- boards/pimoroni-pico-lipo-16mb/src/lib.rs
- boards/rp-pico/Cargo.toml
- boards/rp-pico/examples/pico_i2c_pio.rs
- boards/rp-pico/examples/pico_uart_irq_buffer.rs
- boards/rp-pico/examples/pico_uart_irq_echo.rs
- boards/rp-pico/src/lib.rs
- boards/sparkfun-pro-micro-rp2040/src/lib.rs
- rp2040-hal/examples/blinky.rs
- rp2040-hal/examples/multicore_fifo_blink.rs
- rp2040-hal/examples/pwm_blink.rs
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/examples/uart.rs
- rp2040-hal/examples/watchdog.rs
- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/reader.rs
- rp2040-hal/src/uart/utils.rs
- rp2040-hal/src/uart/writer.rs
Demonstrates some methods for getting your HAL peripherals somewhere an interrupt routine can use them.
> UART IRQ examples

- boards/adafruit-feather-rp2040/Cargo.toml
- boards/adafruit-itsy-bitsy-rp2040/Cargo.toml
- boards/adafruit-kb2040/Cargo.toml
- boards/adafruit-macropad/Cargo.toml
- boards/adafruit-qt-py-rp2040/Cargo.toml
- boards/pimoroni-pico-explorer/Cargo.toml
- boards/pimoroni-pico-lipo-16mb/Cargo.toml
- boards/rp-pico/Cargo.toml
- boards/sparkfun-pro-micro-rp2040/Cargo.toml
- rp2040-hal/Cargo.toml
The change to UartPeripheral in #210 was a breaking change:
Bump the version of the HAL and all dependent BSP crates.
> Bump versions of HAL and BSPs

- boards/rp-pico/README.md
The boot selector pin is attached to SPI_SS and not easily read (an
example
https://github.com/raspberrypi/pico-examples/blob/master/picoboard/button/button.c),
since the code reading needs to reside in SRAM.
Simply fix the documentation by only mentioning the pin
> boards/pico: Remove mention of boot select button

- boards/adafruit-kb2040/examples/adafruit_kb2040_rainbow.rs
- boards/rp-pico/examples/pico_uart_irq_buffer.rs
- boards/rp-pico/examples/pico_uart_irq_echo.rs
> Remove static BOOT2 decl in BSP examples so they build

- rp2040-hal/src/pio.rs
Clippy complains about the following line being unsound: [rp2040-hal/src/pio.rs:535](https://github.com/rp-rs/rp-hal/blob/f9b3d8341d9e8e83d6be89ae3692f85646bde97a/rp2040-hal/src/pio.rs#L535)
```
this implementation is unsound, as some fields in `StateMachine<SM, State>` are `!Send`
`#[warn(clippy::non_send_fields_in_send_ty)]` on by default
add bounds on type parameter `SM` that satisfy `InstalledProgram<SM::PIO>: Send`
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#non_send_fields_in_send_ty
```
The warning can be resolved by making PIOExt, StateMachineIndex, and ValidStateMachine be supertraits of Send. This also makes adding the Send bound redundant in a few places.
> pio: Fix unsound Send clippy warning

- .github/workflows/build_and_test.yml
Fix CI BSP examples not generating failure on link errors
#250 exists because CI was not generating errors on failure to link.
This was due to [RUSTFLAGS: "-D warnings" ](https://github.com/9names/rp-hal/blob/c02984b422d3cc12e14a3e17373f7bb3b57e5e58/.github/workflows/build_and_test.yml#L8) suppressing the link errors.
In this PR:
- I remove "-D warnings" from RUSTFLAGS, to ensure we don't mask our warnings like linker error
- switch from `cargo check` to `cargo build` so we test linking, and also add release builds to the workflow in case they get build errors.
> Fix ci masking link errors

- boards/rp-pico/Cargo.toml
- boards/rp-pico/README.md
- boards/rp-pico/examples/pico_spi_sd_card.rs
Hi!
I've connected an SD card to my Raspberry Pi Pico now and successfully used the `embedded_sdmmc` crate with it.
I cleaned up my example code and added diagnostics LED signals to get feedback even without a debugging probe.
I hope it's okay to add defmt to the dev-dependencies, even though the examples use the UF2 upload of the Pico.
> Add an example for accessing an SD/MMC card via SPI

- Cargo.toml
- boards/solderparty-rp2040-stamp/Cargo.toml
- boards/solderparty-rp2040-stamp/README.md
- boards/solderparty-rp2040-stamp/examples/solderparty_stamp_neopixel_rainbow.rs
- boards/solderparty-rp2040-stamp/src/lib.rs
Add support for the [RP2040 Stamp board](https://www.solder.party/docs/rp2040-stamp/) by Solder Party.
This board has a single "device" - a neopixel. The example I included for this is copied and updated from the feather board example.
> Add Solder Party RP2040 Stamp board

- boards/rp-pico/src/lib.rs
- rp2040-hal/src/gpio/pin.rs
I don't know if this is useful or if it is out of scope of the board specific documentation, but I quickly (half automatically via script) converted the rp2040 datasheet section 1.4.3 to board specific pin documentation.
Like I already wrote on Matrix, I would love to do this for `rp2040_hal::gpio::pin::bank0` too, but the macro does not support documentation meta information and I don't know how to add it.
> Added pin function documentation from the datasheet to rp-pico

- boards/rp-pico/Cargo.toml
- boards/rp-pico/examples/pico_i2c_oled_display_ssd1306.rs
Hi,
here is another example to get newcomers started with Rust on the Raspberry Pi Pico. It's a for a more or less regular 128x64 OLED Display you can find either on AliExpress or Amazon.
I hope it's okay adding lots of examples, I know that these help a great deal when trying to get familiar with the embedded Rust ecosystem.
> Pico i2c oled text display ssd1306 example

- rp2040-hal/src/i2c/controller/embassy_support.rs
I noticed that it was always generating a restart condition rather than only reading a byte.
This fixes that issue.
> embassy-traits: Fix unexpected restart on repeated read.

- Cargo.toml
- README.md
- boards/adafruit-trinkey-qt2040/Cargo.toml
- boards/adafruit-trinkey-qt2040/README.md
- boards/adafruit-trinkey-qt2040/examples/adafruit_trinkey_qt2040_rainbow.rs
- boards/adafruit-trinkey-qt2040/src/lib.rs
Includes rainbow example. Tested on a board plugged into a Pi 4 Model B.
> Board support for Adafruit Trinkey QT2040

- boards/adafruit-kb2040/Cargo.toml
- boards/adafruit-kb2040/src/lib.rs
I missed this one when updating the others to boot2, maybe this PR was still in progress?
> Add boot2 feature to kb2040 BSP

- rp2040-hal/examples/uart.rs
The original uart example passed the peripheral clock by calling
```rust
clocks.peripheral_clock.into()
```
which *moves* the peripheral clock, not very helpful for an example.
By getting an integer representation first via
```rust
clocks.peripheral_clock.freq(),
```
we get a copy of the value so other peripherals (like a 2nd UART) can still be initialised
> Use .freq() to avoid moving clock

- rp2040-hal/Cargo.toml
- rp2040-hal/examples/dht11.rs
This example reads a dht11 sensor using a simulated open-drain pin.
Closes rp-rs/rp-hal#274
> Add an example reading a dht11 sensor

- rp2040-hal/src/sio.rs
This implements intrinsics for the hardware divider so normal operators use it instead of the default software implementations.  So with this applied `/` and `%` operations should make use of the hardware divider.  This also makes access to the divider interrupt safe by implementing the save/restore logic used by the Pico SDK. 
Unsurprisingly, there's quite a bit of room for optimization here, when you compare the generated assembly to that hand optimized version in the Pico SDK.  However, in my testing it still results in about a 60% speedup compared to the default software implementations.
To be honest, I'm not completely sure why the override works correctly: the functions defined by [compiler-builtins intrinsics macro](https://github.com/rust-lang/compiler-builtins/blob/ea0cb5b589cc498 …
> Implement intrinsics for the hardware divider

- boards/rp-pico/examples/pico_rtic.rs
- rp2040-hal/src/timer.rs
The existing Alarm implementation uses register.modify() calls to access the interrupt manipulation registers.
To make this a little safer, the original implementer made them all take &mut Timer to ensure there wasn't a data race when performing that RMW.
That's great for safety, but bad for ergonomics.
This PR uses the atomic_clear and atomic_set functions to avoid these data races.
Functionality is largely the same as the PWM interrupt interactions, example:
https://github.com/rp-rs/rp-hal/blob/5771f872f2d08af821ea405d09d12e3d404996b5/rp2040-hal/src/pwm/mod.rs#L385-L391
> Use atomic operations for altering Timer alarm interrupts

- boards/rp-pico/examples/pico_ws2812_led.rs
- rp2040-hal/Cargo.toml
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/src/rom_data.rs
First, this standardizes ROM function access between the floating point and normal functions.  It makes the direct call (e.x. `hal::rom_data::popcount32(0xFF)`) do the operation, while also adding a module with the same name as the function and `ptr()` function to get a function pointer for local caching.  So there are now two ways to access every ROM function:
```rust
let result = hal::rom_data::popcount32(0xFF);
let pc32 = hal::rom_data::popcount32::ptr();
let result = pc32(0xFF);
```
This represents an API change for the floating point functions, but a simple one: the previous API is just the `::ptr()` call.
Next, it implements a crate feature (`rom-cache`) to enable automatic caching via static variables of the ROM table lookups.  The actual savings varies based on the function call …
> Improve ROM function access

- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/src/gpio/dynpin.rs
- rp2040-hal/src/gpio/pin.rs
- rp2040-hal/src/i2c/controller.rs
- rp2040-hal/src/pwm/mod.rs
- rp2040-hal/src/spi.rs
- rp2040-hal/src/timer.rs
- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/reader.rs
- rp2040-hal/src/uart/writer.rs
- rp2040-hal/src/watchdog.rs
- Several traits were removed from embedded-hal (https://github.com/rust-embedded/embedded-hal/pull/324/, https://github.com/rust-embedded/embedded-hal/pull/354), so this pull request also removes them.
- Some new functions were added to the I2C traits. Those have not been tested, yet.
> Implement embedded-hal 1.0.0-alpha.7 traits

- .github/workflows/build_and_test.yml
- rp2040-hal/CHANGELOG.md
- rp2040-hal/src/clocks/macros.rs
- rp2040-hal/src/clocks/mod.rs
While looking at the code generated by https://github.com/rp-rs/rp-hal/pull/288, I wondered why there were references to 64bit division code (`compiler_builtins::int::specialized_div_rem::u64_div_rem`) for a basically empty firmware.
Turned out that `init_clocks_and_plls()` contained 64bit integer divisions.
As the code to do those divisions takes about 1kB even in fully optimized builds, I changed the clock calculation code to use 32bit divisions, instead.
To keep the code small, I accepted some minimal additional rounding error: In case the remainder of the division is bigger than 2^24, the lower 8 bits will be thrown away, causing a relative rounding error of at most 2^-16.
(To be exact, instead of the expected rounding-down of normal integer division, the value might get rounded up, …
> Avoid 64bit division

- boards/adafruit-feather-rp2040/Cargo.toml
- boards/adafruit-itsy-bitsy-rp2040/Cargo.toml
- boards/adafruit-kb2040/Cargo.toml
- boards/adafruit-qt-py-rp2040/Cargo.toml
- boards/adafruit-trinkey-qt2040/Cargo.toml
- boards/rp-pico/Cargo.toml
- boards/solderparty-rp2040-stamp/Cargo.toml
- boards/sparkfun-pro-micro-rp2040/Cargo.toml
- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/examples/pio_proc_blink.rs
- rp2040-hal/examples/pio_side_set.rs
- rp2040-hal/src/pio.rs
Some last-minute tidy ups for the 0.4.0 release.
- Updated to pio 0.2.0 and pio-proc 0.2.0, and migrated the HAL examples to match
- IRQ example wasn't building since it required HAL to be build with features = ["rt"] but that wasn't specified
- Updated the changelog
> Prep for 0.4.0 release

- boards/adafruit-feather-rp2040/CHANGELOG.md
- boards/adafruit-feather-rp2040/Cargo.toml
- boards/adafruit-feather-rp2040/README.md
- boards/adafruit-itsy-bitsy-rp2040/CHANGELOG.md
- boards/adafruit-itsy-bitsy-rp2040/Cargo.toml
- boards/adafruit-itsy-bitsy-rp2040/README.md
- boards/adafruit-kb2040/CHANGELOG.md
- boards/adafruit-kb2040/Cargo.toml
- boards/adafruit-kb2040/README.md
- boards/adafruit-macropad/CHANGELOG.md
- boards/adafruit-macropad/Cargo.toml
- boards/adafruit-macropad/README.md
- boards/adafruit-qt-py-rp2040/CHANGELOG.md
- boards/adafruit-qt-py-rp2040/Cargo.toml
- boards/adafruit-qt-py-rp2040/README.md
- boards/pimoroni-pico-explorer/CHANGELOG.md
- boards/pimoroni-pico-explorer/Cargo.toml
- boards/pimoroni-pico-explorer/README.md
- boards/pimoroni-pico-lipo-16mb/CHANGELOG.md
- boards/pimoroni-pico-lipo-16mb/Cargo.toml
- boards/pimoroni-pico-lipo-16mb/README.md
- boards/pimoroni-tiny2040/Cargo.toml
- boards/rp-pico/CHANGELOG.md
- boards/rp-pico/Cargo.toml
- boards/rp-pico/README.md
- boards/solderparty-rp2040-stamp/README.md
- boards/sparkfun-pro-micro-rp2040/CHANGELOG.md
- boards/sparkfun-pro-micro-rp2040/Cargo.toml
- boards/sparkfun-pro-micro-rp2040/README.md
- rp2040-hal/README.md
Now that HAL 0.4.0 is out we can think about publishing updates for all the BSPs.
I thought it would be a good idea to try to get them a little bit more consistent first.
There's also an update for the HAL readme that I missed before pressing the publish button.
I won't push a new version of the HAL until we accumulate a bunch of bug-fixes
> Update BSPs prior to release

- Cargo.toml
- rp2040-hal-macros/Cargo.toml
- rp2040-hal-macros/README.md
- rp2040-hal-macros/src/lib.rs
- rp2040-hal/Cargo.toml
- rp2040-hal/src/lib.rs
This macro extends the one from cortex-m-rt by code to unlock all spinlocks on boot.
I wonder if this should be part of the HAL, or if it belongs to rp2040-pac.
Closes #292
> Add an rp2040 specific #[entry] macro.

- rp2040-hal/examples/pio_synchronized.rs
- rp2040-hal/src/pio.rs
This adds a bunch of boiler-plate structs to pio.rs, but is the easiest way I found to solve #286. Any idea for a better implementation is welcome.
The resulting API is fine though, as those types do not become visible:
```
// Start both SMs at the same time
let group = sm0.with(sm1).sync().start();
// Stop both SMs at the same time
let group = group.stop();
// Start them again and extract the individual state machines
let (sm1, sm2) = group.start().free();
// Stop the two state machines separately
let _sm1 = sm1.stop();
let _sm2 = sm2.stop();
```
(Context: https://github.com/jannic/rp-hal/blob/9b625a573e0ad05c699845239ab3fdb2cae75fd1/rp2040-hal/examples/pio_synchronized.rs#L78-L93)
Closes #286
> Allow to start multiple state machines in sync

- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/writer.rs
For details, see #284.
The approach was initially suggested by @danielzfranklin. I just filed the PR and did some hardware testing.
Changes were successfully tested by using UART for ESP8266 Wi-Fi offloading in combination with RTIC.
There are perhaps better ways to solve this problem, so I'm looking forward to your feedback.
> Using thread send safe UART* marker, when splitting

- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/reader.rs
As @Liamolucko noticed in #310, the UART code stores some config values in its structs which are never used.
While it's possible that future extensions actually need those fields, I don't think it's reasonable to keep them just in case, without a near-term plan to actually use them.
Closes #310
> Remove some unused fields from UartPeripheral and Reader

- rp2040-hal/src/float/div.rs
- rp2040-hal/src/intrinsics.rs
- rp2040-hal/src/sio.rs
This implements the hardware divider usage directly in assembler.  The result is a significant speedup in the common (no state save required) case as well as a small one when a state save is required.
In truth, I'm not sure this specific variant is the best option (see below), because blocks of assembler are always hard to maintain.  The reason I ultimately decided on this variant was simply because division is common enough that having it be as fast as possible seemed worth the tradeoff of some gnarly code.  If I could have found a way to convince the compiler to eliminate the shims/prologues from the pure Rust implementation, then that would likely be superior: it would only sacrifice some performance in the less common save/restore case. 
This PR currently requires a nightly compiler. …
> Use optimized assembly for hardware division

- boards/rp-pico/examples/pico_rtic.rs
- rp2040-hal/src/sio.rs
RTIC-based examples can't make use of the hal::entry macro to reset all spinlocks.
Provide an unsafe fn() that can be used to reset all spinlocks in init()
> Provide an unsafe function for resetting all spinlocks

- boards/adafruit-macropad/Cargo.toml
- boards/adafruit-macropad/examples/adafruit-macropad_blinky.rs
- boards/adafruit-macropad/src/lib.rs
Also adds const XOSC_CRYSTAL_FREQ = 12_000_000, which is the right
value according to https://learn.adafruit.com/assets/103270
Fixes #302
> Add adafruit-macropad_blinky example

- Cargo.toml
- README.md
- boards/sparkfun-thing-plus-rp2040/CHANGELOG.md
- boards/sparkfun-thing-plus-rp2040/Cargo.toml
- boards/sparkfun-thing-plus-rp2040/README.md
- boards/sparkfun-thing-plus-rp2040/examples/sparkfun_thing_plus_rainbow.rs
- boards/sparkfun-thing-plus-rp2040/src/lib.rs
Provides some rudimentary support for the SparkFun Thing Plus RP2040 board. For the most part, this just follows the example set by the BSP for the Pro Micro RP2040, just changing the aliases where appropriate. I've confirmed that the Rainbow example works on the board, too.
> Initial BSP for SparkFun Thing Plus RP2040

- README.md
- boards/adafruit-feather-rp2040/README.md
- boards/adafruit-itsy-bitsy-rp2040/README.md
- boards/adafruit-kb2040/README.md
- boards/adafruit-macropad/README.md
- boards/adafruit-qt-py-rp2040/README.md
- boards/adafruit-trinkey-qt2040/README.md
- boards/pimoroni-pico-explorer/README.md
- boards/pimoroni-pico-lipo-16mb/README.md
- boards/pimoroni-plasma-2040/README.md
- boards/pimoroni-tiny2040/README.md
- boards/rp-pico/README.md
- boards/solderparty-rp2040-stamp/README.md
- boards/sparkfun-pro-micro-rp2040/README.md
- boards/sparkfun-thing-plus-rp2040/README.md
Found a minor typo that appears to have been copied and pasted into all of this project's subcrates (including the one I just contributed, whoops!). Nothing a little `sed` command can't fix.
> Fix typo in License section of READMEs

- boards/rp-pico/examples/pico_usb_twitchy_mouse.rs
This fixes the mouse on Mac.
Closes #327
> Set device_class of twitchy_mouse example to 0

- boards/sparkfun-pro-micro-rp2040/src/lib.rs
The sparkfun-pro-micro-2040 pins definition was missing the copi pin on gpio 23, see https://cdn.sparkfun.com/assets/e/2/7/6/b/ProMicroRP2040_Graphical_Datasheet.pdf for reference from sparkfun.
> Add missing copi pin for sparkfun-pro-micro-2040

- rp2040-hal/src/i2c.rs
This PR adds the missing I2C trait implementations for `Gpio`s 22-25 and 28+29. This is in line with the datasheet (p14) which lists all GPIOs to be I2C-capable.
> Add missing GPIO I2C trait implmentations

- boards/adafruit-feather-rp2040/Cargo.toml
- boards/adafruit-itsy-bitsy-rp2040/Cargo.toml
- boards/adafruit-kb2040/Cargo.toml
- boards/adafruit-macropad/Cargo.toml
- boards/adafruit-qt-py-rp2040/Cargo.toml
- boards/adafruit-trinkey-qt2040/Cargo.toml
- boards/arduino_nano_connect/Cargo.toml
- boards/pimoroni-pico-explorer/Cargo.toml
- boards/pimoroni-pico-lipo-16mb/Cargo.toml
- boards/pimoroni-plasma-2040/Cargo.toml
- boards/pimoroni-tiny2040/Cargo.toml
- boards/rp-pico/Cargo.toml
- boards/solderparty-rp2040-stamp/Cargo.toml
- boards/sparkfun-pro-micro-rp2040/Cargo.toml
- boards/sparkfun-thing-plus-rp2040/Cargo.toml
- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
Update the changelog with all HAL changes, bump version number
> Prep for HAL 0.5.0 release

- boards/adafruit-feather-rp2040/CHANGELOG.md
- boards/adafruit-feather-rp2040/Cargo.toml
- boards/adafruit-itsy-bitsy-rp2040/CHANGELOG.md
- boards/adafruit-itsy-bitsy-rp2040/Cargo.toml
- boards/adafruit-kb2040/CHANGELOG.md
- boards/adafruit-kb2040/Cargo.toml
- boards/adafruit-macropad/CHANGELOG.md
- boards/adafruit-macropad/Cargo.toml
- boards/adafruit-qt-py-rp2040/CHANGELOG.md
- boards/adafruit-qt-py-rp2040/Cargo.toml
- boards/adafruit-trinkey-qt2040/Cargo.toml
- boards/arduino_nano_connect/Cargo.toml
- boards/pimoroni-pico-explorer/CHANGELOG.md
- boards/pimoroni-pico-explorer/Cargo.toml
- boards/pimoroni-pico-lipo-16mb/CHANGELOG.md
- boards/pimoroni-pico-lipo-16mb/Cargo.toml
- boards/pimoroni-plasma-2040/Cargo.toml
- boards/pimoroni-tiny2040/Cargo.toml
- boards/rp-pico/CHANGELOG.md
- boards/rp-pico/Cargo.toml
- boards/solderparty-rp2040-stamp/Cargo.toml
- boards/sparkfun-pro-micro-rp2040/CHANGELOG.md
- boards/sparkfun-pro-micro-rp2040/Cargo.toml
- boards/sparkfun-thing-plus-rp2040/CHANGELOG.md
- boards/sparkfun-thing-plus-rp2040/Cargo.toml
As the BSPs re-export the hal, their version needs to be bumped after the release of rp2040-hal.
Also updates the changelogs and removes broken links.
> Bump version of board support crates

- boards/arduino_nano_connect/Cargo.toml
These deps aren't used and are blocking publishing on crates.io
> Remove unused embassy/embassy-traits deps in arduino-nano-connect

- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
- rp2040-hal/src/adc.rs
For now, this is only updating the dependency, and removing ADC traits which where also removed from embedded-hal.
The new blocking [SPI traits](https://docs.rs/embedded-hal/1.0.0-alpha.8/embedded_hal/spi/blocking/index.html) are not yet implemented.
> Implement embedded-hal 1.0.0-alpha.8 traits

- rp2040-hal/src/intrinsics.rs
While the code block fails to compile, it's still code and not random text. Marking it with `ignore` allows for proper syntax highlighting, for example.
According to https://github.com/rust-lang/rust/issues/97030#issuecomment-1134499264 this is the proper fix, so this closes #374
> Use `ignore` instead of `text`

- rp2040-hal/src/gpio/pin.rs
The link for DynPinMode was a broken. The generated docs looked like this:
after this patch they look like this
> Add missing open paren in bsp_pins doc macro

- boards/seeeduino-xiao-rp2040/src/lib.rs
This updates the name for GPIO pin 2 to match its function, so the naming scheme is consistent across pins within the Seeeduino XIAO RP2040 BSP (#369).
> Match Seeeduino XIAO pin name to function

- boards/rp-pico/examples/pico_i2c_oled_display_ssd1306.rs
- boards/rp-pico/examples/pico_i2c_pio.rs
- boards/rp-pico/examples/pico_uart_irq_buffer.rs
- boards/rp-pico/examples/pico_uart_irq_echo.rs
- rp2040-hal/CHANGELOG.md
- rp2040-hal/examples/adc.rs
- rp2040-hal/examples/i2c.rs
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/src/clocks/macros.rs
- rp2040-hal/src/uart/mod.rs
Implementing `impl From<SystemClock> for Hertz` is a footgun, as
SystemClock is not Copy, so the automatic conversion consumes the
owned clock.
This is visible in the example i2c.rs:
```
let mut i2c = hal::I2C::i2c1(
pac.I2C1,
sda_pin,
scl_pin, // Try `not_an_scl_pin` here
400.kHz(),
&mut pac.RESETS,
clocks.peripheral_clock,
);
```
If the user wants to use both `i2c0` and `i2c1` at the same time,
copying from this example won't work:
```
error[E0382]: use of moved value: `clocks.peripheral_clock`
--> rp2040-hal/examples/i2c.rs:106:9
|
97  |         clocks.peripheral_clock,
|         ----------------------- value moved here
...
106 |         clocks.peripheral_clock,
|         ^^^^^^^^^^^^^^^^^^^^^^^ value used here after move
|
= note: move occurs because `clocks.peripheral_clock` has type …
```
> Implement conversion from Clock to Hertz using reference

- rp2040-hal/examples/gpio_irq_example.rs
The example previously assumed that if the interrupt service routine was running, that the source of the interrupt had to be the button EdgeLow trigger.
While this is true, it does not reflect a real-world usage where other pins or edges may be configured to generate interrupts.
#400 was asking how to do this, so it makes sense to update the example to help others find this information.
> GPIO IRQ example: Check the interrupt source in ISR

- rp2040-hal/src/timer.rs
The only thing accessed by those methods is `&mut self`, which is
guaranteed to be a unique reference. So an interrupt can not
interfere with the correctness of the operation.
> Remove unnecessary cortex_m::interrupt::free in timer.rs

- rp2040-hal/src/usb.rs
Every thing is in the title :) 
Although, it's worth noting that due to a bug in the currently published version of usb-device (0.2.8) this won't work properly.
[A fix](https://github.com/rust-embedded-community/usb-device/pull/97) has been merged already so until it's published on crates.io one has to 
```toml
[patch.crates-io]
usb-device = { git="https://github.com/rust-embedded-community/usb-device" }
```
> Add suspend, resume and remote wakeup support.

- rp2040-hal/src/usb.rs
The ep0-out buffer must not be marked as available unless required.
Otherwise, the controller will acknowledge the data-out packet but won't reflect that in its status registers.
This patch forces the controller to nack the data-out phase until we have processed the setup packet.
As per 4.1.2.5.1, the access to the DPSRAM should "be considered asynchronous and not atomic".
It is recommended to write to buffer control register in two steps.
- A first one to configure all bits but Available.
- Wait clk_sys/clk_usb (typically 125MHz/48MHz).
- Then set the available bit (if required).
The pico-sdk uses a blanket 12tick asm block so proposing a 12tick delay here too.
> Fix usb missed ep0 out packet and add recommended sync delays

- boards/rp-pico/Cargo.toml
- boards/vcc-gnd-yd-rp2040/Cargo.toml
- rp2040-hal/Cargo.toml
This version contains the fix to usb-device support for suspend.
> bump usb-device to 0.2.9

- .cargo/config
- boards/arduino_nano_connect/Cargo.toml
- boards/pimoroni-badger2040/Cargo.toml
- boards/pimoroni-plasma-2040/Cargo.toml
- boards/pimoroni-plasma-2040/build.rs
- boards/pimoroni-tiny2040/Cargo.toml
- boards/pimoroni-tiny2040/build.rs
- boards/rp-pico/Cargo.toml
- boards/rp-pico/build.rs
- boards/vcc-gnd-yd-rp2040/Cargo.toml
Current version of probe-run is 0.3.3, which uses defmt 0.3.2.
With a firmware using defmt 0.2, this causes the following error
message:
```
Error: defmt wire format version mismatch: firmware is using 0.2, `probe-run` supports 3
suggestion: `cargo install` a different version of `probe-run` that supports defmt 0.2
```
Therefore, upgrade defmt dependency, ~~and also fix the linker script
in .cargo/config~~.
**EDIT:** instead of .cargo/config, use build.rs in individual board crates to set linker options as necessary.
> Update examples to defmt 0.3

- rp2040-hal/src/usb.rs
Without those changes I was able to get `pico_usb_twitchy_mouse` into a state where the interrupt was triggered continuously and the main routine didn't make any progress.
> Fix clearing usb sie_status flags

- boards/rp-pico/examples/pico_i2c_pio.rs
- rp2040-hal/examples/dht11.rs
- rp2040-hal/examples/gpio_irq_example.rs
- rp2040-hal/examples/i2c.rs
- rp2040-hal/examples/lcd_display.rs
- rp2040-hal/examples/pio_blink.rs
- rp2040-hal/examples/pio_proc_blink.rs
- rp2040-hal/examples/pio_side_set.rs
- rp2040-hal/examples/pio_synchronized.rs
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/examples/spi.rs
- Clippy warns about empty loops, https://github.com/rust-lang/rust-clippy/issues/6161
- wfi allows to CPU to save some power
WFI was avoided in examples for fear of ill interactions with debuggers.
However the rp2040 debug port does continue to work, as long as the
relevant clocks are not disabled in SLEEP_EN0/SLEEP_EN1. (By default,
all clocks stay enabled in sleep mode.)
This patch replaces several different workarounds with just calling wfi.
> Use wfi in otherwise empty infinite loops in examples

- rp2040-hal/Cargo.toml
- rp2040-hal/examples/adc.rs
- rp2040-hal/examples/blinky.rs
- rp2040-hal/examples/dht11.rs
- rp2040-hal/examples/gpio_in_out.rs
- rp2040-hal/examples/gpio_irq_example.rs
- rp2040-hal/examples/i2c.rs
- rp2040-hal/examples/lcd_display.rs
- rp2040-hal/examples/multicore_fifo_blink.rs
- rp2040-hal/examples/multicore_polyblink.rs
- rp2040-hal/examples/pio_blink.rs
- rp2040-hal/examples/pio_proc_blink.rs
- rp2040-hal/examples/pio_side_set.rs
- rp2040-hal/examples/pio_synchronized.rs
- rp2040-hal/examples/pwm_blink.rs
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/examples/spi.rs
- rp2040-hal/examples/uart.rs
- rp2040-hal/examples/watchdog.rs
Those examples should be independent of a specific board.
The generic boot loader increases their compatibility.
> Use generic boot loader for rp2040-hal examples

- rp2040-hal/Cargo.toml
Without this change, building the vector_table example fails when
building from the rp2040-hal directory:
```
rp2040-hal$ cargo build --release --example vector_table
Compiling rp2040-hal v0.5.0 (rp2040-hal)
error[E0432]: unresolved import `pac::interrupt`
--> rp2040-hal/examples/vector_table.rs:30:5
|
30 | use pac::interrupt;
|     ^^^^^---------
|     |    |
|     |    help: a similar name exists in the module (notice the capitalization): `Interrupt`
|     no `interrupt` in the root
error: cannot determine resolution for the attribute macro `interrupt`
--> rp2040-hal/examples/vector_table.rs:148:3
|
148 | #[interrupt]
|   ^^^^^^^^^
|
= note: import resolution is stuck, try simplifying macro imports
```
> Enable feature "rt" when compiling vector_table example

- rp2040-hal/src/gpio/dynpin.rs
- rp2040-hal/src/pwm/dyn_slice.rs
- rp2040-hal/src/pwm/mod.rs
Fixes a few instances of derive-partial-eq-without-eq and needless-borrow
clippy warnings.
> Fix clippy warnings

- .github/workflows/build_and_test.yml
The workflow only shows "Runs action-rs/cargo@v1" which does not tell us much about what's actually being done.
The list and clean up done after each build varies by only the debug/release part of the path that is repeated several times (2).
This PR gives each step a more meaningful name and simplify the list & clean up step with a generic one liner that can be copy/pasted without modification.
> Add meaningful names to steps and remove quasi-repetition

- boards/pimoroni-plasma-2040/Cargo.toml
- boards/pimoroni-tiny2040/Cargo.toml
- boards/rp-pico/Cargo.toml
This is a little bit hacky, as it relies on rp2040-hal actually
using (and therefore linking) some defmt code when the defmt feature is
enabled.
However this solution has the advantage that it only affects
dev-dependencies and therefore has no impact on the board crates
themselves.
Closes #420
> Enable rp2040-hal/defmt feature in dev-dependencies

- rp2040-hal/src/clocks/mod.rs
The current extended usage clocks example is written correctly but the XOSC needs to be setup first in order for it to work properly. This matches the layout in `init_clocks_and_plls`.
> Fix clocks docs "extended usage" to match `init_clocks_and_plls`

- boards/rp-pico/CHANGELOG.md
- boards/rp-pico/Cargo.toml
- boards/rp-pico/examples/pico_uart_irq_buffer.rs
- boards/rp-pico/examples/pico_uart_irq_echo.rs
- boards/rp-pico/examples/pico_usb_twitchy_mouse.rs
- rp2040-hal/examples/gpio_irq_example.rs
- rp2040-hal/examples/vector_table.rs
For consistency let's use `critical_section` everywhere.
~(There was also a `cortex_m::interrupt::free` left over in `timer.rs`)~
> Replace cortex_m::interrupt::Mutex with critical_section::Mutex in examples

- boards/rp-pico/Cargo.toml
- boards/vcc-gnd-yd-rp2040/Cargo.toml
Just pin the git dependency on the most recent working version
As the failing CI builds are annoying, and https://github.com/rp-rs/rp-hal/pull/426 sparked some discussions, just fix the build by reverting to a working version of embedded-sdmmc.
> Minimal fix for embedded-sdmmc build failure

- rp2040-hal/src/pio.rs
Otherwise, it will change unrelated pindirs as well, if sticky is set
> Temporarily disable out_sticky in set_pindirs

- boards/rp-pico/examples/pico_interpolator.rs
For some reason this didn't get caught by CI.
> Fix interpolator example post migration to fugit

- .github/workflows/build_and_test.yml
- boards/arduino_nano_connect/Cargo.toml
- boards/pimoroni-badger2040/Cargo.toml
- boards/rp-pico/Cargo.toml
- boards/vcc-gnd-yd-rp2040/Cargo.toml
- rp2040-hal-macros/Cargo.toml
Should it be made part of the existing jobs or parallel ones?
> remove unused dependencies & add GHA flow

- boards/pimoroni-badger2040/Cargo.toml
Reverts rp-rs/rp-hal#435
I published it with the _ and this cannot be changed (yet? https://github.com/rust-lang/crates.io/issues/728)
> Revert "Make Pimoroni Badger 2040's crate name consistent with it's directory"

- rp2040-hal/examples/adc.rs
- rp2040-hal/examples/blinky.rs
- rp2040-hal/examples/dht11.rs
- rp2040-hal/examples/gpio_in_out.rs
- rp2040-hal/examples/gpio_irq_example.rs
- rp2040-hal/examples/i2c.rs
- rp2040-hal/examples/lcd_display.rs
- rp2040-hal/examples/multicore_fifo_blink.rs
- rp2040-hal/examples/multicore_polyblink.rs
- rp2040-hal/examples/pio_blink.rs
- rp2040-hal/examples/pio_proc_blink.rs
- rp2040-hal/examples/pio_side_set.rs
- rp2040-hal/examples/pio_synchronized.rs
- rp2040-hal/examples/pwm_blink.rs
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/examples/spi.rs
- rp2040-hal/examples/uart.rs
- rp2040-hal/examples/vector_table.rs
- rp2040-hal/examples/watchdog.rs
Clarify in rp-hal examples that BOOT2 bootloader setup is unnecessary when using a rp-hal based BSP crate.
> examples: clarify usage of boot2 section

- rp2040-hal/examples/vector_table.rs
This PR aligns the `vector_table` example with the other examples from `rp2040-hal`.
> Use rp2040_boot2::BOOT_LOADER_GENERIC_03H in the vector-table example

- boards/adafruit-feather-rp2040/Cargo.toml
- boards/adafruit-itsy-bitsy-rp2040/Cargo.toml
- boards/adafruit-kb2040/Cargo.toml
- boards/adafruit-macropad/Cargo.toml
- boards/adafruit-qt-py-rp2040/Cargo.toml
- boards/adafruit-trinkey-qt2040/Cargo.toml
- boards/arduino_nano_connect/Cargo.toml
- boards/pimoroni-badger2040/Cargo.toml
- boards/pimoroni-pico-explorer/Cargo.toml
- boards/pimoroni-pico-lipo-16mb/Cargo.toml
- boards/pimoroni-plasma-2040/Cargo.toml
- boards/pimoroni-tiny2040/Cargo.toml
- boards/rp-pico/Cargo.toml
- boards/seeeduino-xiao-rp2040/Cargo.toml
- boards/solderparty-rp2040-stamp/Cargo.toml
- boards/sparkfun-pro-micro-rp2040/Cargo.toml
- boards/sparkfun-thing-plus-rp2040/Cargo.toml
- boards/vcc-gnd-yd-rp2040/Cargo.toml
- rp2040-hal/Cargo.toml
There are a lot of non-binary crates depending on rp2040-hal. That way, the default-features of rp2040-hal may be activated unintentionally through an indirect dependency. Therefore, a binary crate which wants to disable the `critical-section-impl` feature to provide its own one could have a hard time to do so.
In contrast, the board support crates are usually only used by top-level binary crates. So disabling the default features on those should usually just work.
Binary crates depending on rp2040-hal directly, which don't use any board support crate, might need to activate the feature manually. This is reasonable because those binary crates need to replicate some boilerplate from the board crates anyhow.
> Enable critical-section-impl by default only from board crates, not from hal

- rp2040-hal/src/pio.rs
The SM knows its id using the type system so there's no need for checking it.
This commit also adds a `PioIRQ` enum to select the output IRQ.
EDIT: For an example of how I use this: https://github.com/ithinuel/rp2040-async-i2c/blob/main/src/pio.rs
> pio: Move interrupt related (en|dis)abling/forcing methods to the statemachine

- Cargo.toml
- boards/rp-pico/examples/pico_pio_pwm.rs
- rp2040-hal/src/pio.rs
This also includes an alternative implementation of the install function with the hope that using pattern matching will give more opportunity to the compiler to prune the branches we are not interested in.
> fix concurrent accesses to sm_execctrl and sm_instr when sideset isn't optional

- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/reader.rs
- rp2040-hal/src/uart/utils.rs
- rp2040-hal/src/uart/writer.rs
I added the possibility to enable/disable the UART Rx/tx FIFOs as well as setting the watermark for the Rx/Tx  FIFO independently.
I removed the watermark setting on the enable_rx_interrupt function. Since the default value for the watermark is the same as the one set in the enable_rx_interrupt function, it is backward compatible.
> Added set_fifos/set_rx_watermark/set_tx_watermark

- boards/adafruit-itsy-bitsy-rp2040/examples/adafruit_itsy_bitsy_rainbow.rs
- boards/adafruit-qt-py-rp2040/examples/adafruit_qt_py_rp2040_rainbow.rs
- boards/pimoroni-plasma-2040/examples/pimoroni_plasma_2040_blinky.rs
- boards/seeeduino-xiao-rp2040/examples/seeeduino_xiao_rp2040_blinky.rs
- rp2040-hal/src/gpio/pin.rs
With just `into_push_pull_output`, the pin may be driven to the wrong level for a short moment between setting the pin to output and setting the right level.
Using `into_push_pull_output_in_state` avoids that.
> Provide rp2040_hal::gpio::pin::Pin::into_push_pull_output_in_state

- rp2040-hal/src/spi.rs
When using non blocking read/write with CS managed by user, this function permits to deassert CS at the right time.
> added SPI is_busy function

- boards/pimoroni-servo2040/README.md
- boards/pimoroni-servo2040/examples/pimoroni_servo2040_pwm_servo.rs
- boards/pimoroni-servo2040/src/lib.rs
The servo example included phase correction, which does not work with the provided divider. Updated comments to explain numbers and also explain alternate calculation with phase correction enabled.
Remove unusable aliases from all servo pins. The board includes a 180 Ohm resistor on all servo data pins, which makes the lines not very usable for Spi, Uart or I2C. The aliases were removed given they will rarely, if ever, be used with this board.
> Fix servo example in rp2040-servo, remove unusable aliases.

- rp2040-hal/src/watchdog.rs
With the migration to fugit in #361 the watchdog counter calculation was inadvertently changed.  The watchdog tick rate is set to 1 microsecond by [`init_clocks_and_plls`](https://github.com/rp-rs/rp-hal/blob/eac51cdd160cfd6db6937a8d22fdb76a761e823c/rp2040-hal/src/clocks/mod.rs#L333) however the reload counter was changed to milliseconds with the switch.  The misleading field name `delay_ms` presumably contributed to this.
This PR fixes the counter reload units back to microseconds and renames the field to `delay_us` to remove the confusion.
> Fix watchdog counter load

- rp2040-hal/CHANGELOG.md
- rp2040-hal/src/uart/reader.rs
The current handling of a UART error does not accurately report the data before the error.  It currently just returns the whole buffer passed, which will potentially have been partly written by any data read before the error.  Fix this by returning the slice of data that has been read so far.
Also fix a spelling error in the field name.
> Fix UART read error discard data

- rp2040-hal/Cargo.toml
Not perfect, but at least leads to a meaningful error message when the feature is missing:
```
error: target `vector_table` in package `rp2040-hal` requires the features: `rt`, `critical-section-impl`
Consider enabling them by passing, e.g., `--features="rt critical-section-impl"`
```
> Specify required feature critical-section-impl for some examples

- rp2040-hal/src/multicore.rs
- rp2040-hal/src/pll.rs
- rp2040-hal/src/rtc/datetime_no_deps.rs
- rp2040-hal/src/uart/utils.rs
- rp2040-hal/src/xosc.rs
pll and xosc Error types didn't implement Debug, which made them annoying to work with.
And only a few of our Error types implemented derive(defmt::Format).
I added both to all the errors I could find to make things a little more consistent.
> Add derive(Debug) and derive(defmt::Format) to error types

- rp2040-hal/src/spi.rs
This PR implements the latest embedded-hal v1.0.0-alpha.9 SPI traits (just the blocking traits). 
Took advice straight from the repo to do it.
https://github.com/rust-embedded/embedded-hal/blob/9eb6dabe4694d7bf6400de7c10665d6439b0f370/embedded-hal/src/spi.rs#L132-L142
```markdown
HALs **must** implement [`SpiBus`], [`SpiBusRead`] and [`SpiBusWrite`]. Users can combine the bus together with the CS pin (which should
implement [`OutputPin`](crate::digital::blocking::OutputPin)) using HAL-independent [`SpiDevice`] implementations such as the ones in [`embedded-hal-bus`](https://crates.io/crates/embedded-hal-bus).
HALs may additionally implement [`SpiDevice`] to **take advantage of hardware CS management**, which may provide some performance
benefits. (There's no point in a HAL implementing …
```
> implement embedded-hal aplha SPI traits

- boards/rp-pico/examples/pico_usb_serial.rs
Not sure if it should be added here, or as a separate example. But as the question how one can write formatted strings to USB serial has been asked more than once, having some example available would be nice.
> Extend pico_usb_serial example with some string formatting

- rp2040-hal/src/pio.rs
The wrap source and target cannot change after installing the program
into the PIO at present, even though this is possible with the C/C++
HAL. This is useful when using the same program across multiple state
machines that have different wrap sources and targets.
> Add ability to modify installed program wrap bounds

- rp2040-hal/src/critical_section_impl.rs
- rp2040-hal/src/lib.rs
- rp2040-hal/src/sio.rs
Also make Spinlock31 public if it's not used by the critical section impl
> Avoid dead_code warning if critical-section-impl is not enabled

- Cargo.toml
- README.md
- boards/waveshare-rp2040-zero/CHANGELOG.md
- boards/waveshare-rp2040-zero/Cargo.toml
- boards/waveshare-rp2040-zero/README.md
- boards/waveshare-rp2040-zero/examples/waveshare_rp2040_zero_neopixel_rainbow.rs
- boards/waveshare-rp2040-zero/src/lib.rs
This adds the board config for the Waveshare RP2040 Zero board.
I also copied the NeoPixel example from the feather board, but didn't copy the blinky example as the board only has that single Neopixel LED.
I successfully compiled and ran the waveshare_rp2040_zero_neopixel_rainbow example on the board.
> Add Waveshare RP2040 Zero board

- rp2040-hal/src/pio.rs
The documentation of CLKDIV_RESTART contains the following sentence:
"Note also that CLKDIV_RESTART can be written to whilst the state machine is running, and this is useful to resynchronise clock dividers after the divisors (SMx_CLKDIV) have been changed on-the-fly."
This implies that it's allowed to change the value of CLKDIV on a running state machine.
> Allow setting clock divisors on running state machines

- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
- rp2040-hal/src/critical_section_impl.rs
Critical-section 0.2 may be yanked soon, so we should remove the dependency and release a version 0.7.0.
> Remove support for deprecated version 0.2 of critical-section

- boards/pimoroni-plasma-2040/Cargo.toml
- boards/pimoroni-servo2040/Cargo.toml
- boards/pimoroni-tiny2040/Cargo.toml
- boards/rp-pico/Cargo.toml
Version 0.3.0 depends on deprecated critical-section 0.2
> Update dependencies on defmt-rtt to 0.4.0

- rp2040-hal/src/usb.rs
If the latency is too high, there is a risk that the status reverts to a previous state while keeping the interrupt flag up. This fixes that by relying on ints instead of sie_status to process the events.
This should fix the issue reported by @jhillyerd in #492.
> usb: Read ints rather than sie_status in poll

- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/src/critical_section_impl.rs
This is meant to be released as v0.6.1 immediately, to fix failing builds caused by the release of critical-section 0.2.8.
(visit the rust-embedded [chat](https://matrix.to/#/#rust-embedded:matrix.org) for [details](https://libera.irclog.whitequark.org/rust-embedded/2022-11-29#33428525))
> Upgraded dependency on critical-section 0.2 to 0.2.8

- rp2040-hal/src/usb.rs
**Issue**
While using `usb_device` and `usbd_serial` crates with `rp2040_hal`, the first frame from the host device is always getting lost. Consecutive frames work just fine.
**Root Cause**
The `LENGTH_0` region of the `EP_BUFFER_CONTROL` register is always reset (0) while waiting for the first frame. After the first frame failure, the poll operation implicitly sets it  to the necessary value (`max_packet_size`) and this clears the problem for the rest of the app execution lifetime.
The main problem is while resetting and readjustment of the bits needs a step by step operation to avoid potential issues. While doing that and setting `AVAILABLE` bit, the wrong method had been chosen and was invalidating previous changes. Hence the `LENGTH_0` param is reset, too.
**Proposed Solution** …
> Fixed: First frame is getting lost on an USB-CDC device.

- Cargo.toml
- README.md
- boards/waveshare-rp2040-lcd-0-96/CHANGELOG.md
- boards/waveshare-rp2040-lcd-0-96/Cargo.toml
- boards/waveshare-rp2040-lcd-0-96/README.md
- boards/waveshare-rp2040-lcd-0-96/examples/waveshare_rp2040_lcd_demo.rs
- boards/waveshare-rp2040-lcd-0-96/src/lib.rs
This adds the board config for the Waveshare RP2040 LCD 0.96" board.
Board has:
* 0.96inch 160×80 pixels 65K colorful IPS LCD display with ST7735S controller
* Lithium battery recharge/discharge header, suitable for mobile devices
* Onboard DC-DC chip TPS63000, high-efficiency DC-DC buck-boost chip, 1.8A current switch
* 16MBit W25Q16JVUXIQ flash chip.
I successfully compiled and ran the waveshare_rp2040_lcd_demo example on the board.
> Add board waveshare-rp2040-lcd-0.96

- rp2040-hal/src/timer.rs
While reviewing some other merge request, I first read that comment as "in the past some value was set" instead of "the value we just set is already in the past". This is just a minor rewording to avoid that ambiguity.
> Disambiguate a comment

- rp2040-hal/examples/pio_side_set.rs
- rp2040-hal/src/gpio/pin.rs
Some thoughts about the API, `pub fn id(&self) -> DynPinId`
Pro:
- identical to `DynPin::id`
- provides full information about the pin id, including the group (`Bank0` vs. `Qspi`)
Contra:
- the name `DynPinId` of the return type doesn't fit well
- most users won't be interested in the pin id, but only the pin number, requiring a slightly ugly invocation, like `pin.id().num`
Alternatives:
- Just returning the pin number as the result of `id()` could be confusing because of the difference to `DynPin::id`.
- We could add `pub fn num(&self) -> u8` instead, or in addition to `pub fn id(&self) -> DynPinId`
> Add Pin::id()

- .github/workflows/build_and_test.yml
- .github/workflows/clippy.yml
- .github/workflows/rustfmt.yml
I noticed in https://github.com/rp-rs/rp-hal/actions/runs/3751431401 that the github workflow triggers a lot of deprecation warnings. This pull request should fix some of them.
> Update github actions

- .github/workflows/build_and_test.yml
Alternative implementation of #533. Downloads and unpacks a specific release version of of cargo-udeps to use in CI instead of using the unreliable github action.
> Use prebuilt cargo-udeps binary in CI

- rp2040-hal/src/timer.rs
This mentions that `finished()` will also return `false` if the alarm has _not_ been scheduled yet. The implementation of `finished()` checks for the `ARMED` bit, which (AFAICT from the datasheet, "Section 4.6.3. Alarms") is only set when the alarm is scheduled (with `schedule_at()`.
> Clarify 'finished()' behavior for alarms

- .github/workflows/build_and_test.yml
- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
We don't have a documented MSRV policy for rp-hal, but I think https://github.com/rust-embedded/embedded-hal/blob/master/docs/msrv.md is a reasonable approach.
Without any checks in CI we won't notice if we accidentally break compatibility with the documented MSRV. Therefore, I added a (simple) check, which just runs `cargo build --workspace --examples ${{ matrix.features }}` with the old compiler version.
This should not block future changes breaking MSRV compatibility. It's just for awareness, so we can properly document the minimum rust version necessary to build rp2040-hal.
> Document MSRV as 1.62 and add CI check

- rp2040-hal/src/sio.rs
The C/C++ SDK (and datasheet) make use of `base01` (called `base_1and0` in PAC and `INTERP0_BASE_1AND0`/`INTERP1_BASE_1AND0` in datasheet)
https://github.com/raspberrypi/pico-examples/blob/master/interp/hello_interp/hello_interp.c#L132-L140
This PR adds access to this register which is needed for the `simple_blend3` example from the C/C++ SDK.
The `simple_blend3` and `linear_interpolation` examples are also currently missing from https://github.com/rp-rs/rp-hal-boards/blob/main/boards/rp-pico/examples/pico_interpolator.rs .  I'll be opening a PR to addd these shortly.
> Add set_base_1and0 used by simple_blend3 interp example

- rp2040-hal/CHANGELOG.md
- rp2040-hal/src/clocks/mod.rs
- rp2040-hal/src/dma/mod.rs
- rp2040-hal/src/dma/single_channel.rs
- rp2040-hal/src/float/mod.rs
- rp2040-hal/src/gpio/pin.rs
- rp2040-hal/src/pio.rs
- rp2040-hal/src/pll.rs
- rp2040-hal/src/rosc.rs
- rp2040-hal/src/sio.rs
- rp2040-hal/src/spi.rs
- rp2040-hal/src/timer.rs
- rp2040-hal/src/uart/pins.rs
- rp2040-hal/src/uart/utils.rs
- rp2040-hal/src/xosc.rs
Sealing traits allows for later extensions without causing a breaking change.
Reference: https://rust-lang.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed
> Seal several traits

- rp2040-hal/Cargo.toml
- rp2040-hal/examples/pwm_irq_input.rs
- rp2040-hal/src/pwm/mod.rs
Remove `pwm::PwmPinToken` to allow the use of interrupt and pad configuration of `Pins` that are being used with PWM Slices.
Add `pwm_irq_input` example to demonstrate using PWM with interrupts to read a 50 Hz servo PWM input signal and control the pico LED.
> Remove `pwm::PwmPinToken` and add PWM IRQ Input example

- rp2040-hal/src/pio.rs
There is no way to set mov_status with the base hal. Added set_mov_status to allow config of the mov_status variable.
> Added set_mov_status_config function to PIOBuilder

- README.md
The current command gives an error,
the `--chip` and `--list-probes` flags cannot be used at the same time.
This patch fixes the command in the readme.
> Fix probe-run command in readme

- rp2040-hal/src/adc.rs
The code that the link refers to has been moved to another repo.
This patch fixes the link.
> Fix a broken link in docs

- memory.x
This defines new memory regions SRAM4, SRAM5.
Without a linker section referring to those regions, they will not actually be used.
> Document RAM banks in memory.x

- rp2040-hal/src/dma/bidirectional.rs
By reading the code, this seems to be a bug, caused by a typo. The function `check_irq0()` seems to be intended to check `irq0` for both channels. But for channel 1, it is set to check `irq1`.
The corresponding function `check_irq1()` does check `irq1` for both channels.
> Fix DMA IRQ issue for bidirectional DMA transfer

- rp2040-hal/src/timer.rs
This is related to #568. As adding a new parameter to `Timer::new()` would be a breaking change, for now just document that the clocks need to be initialized for the Timer to be usable.
> Mention clock initialization in timer docs

- rp2040-hal/Cargo.toml
- rp2040-hal/src/uart/peripheral.rs
In the current implementation of [`configure_buadrate`](https://github.com/rp-rs/rp-hal/blob/8f6cbd85c255bcd902e32bf41f33be85cd532ca1/rp2040-hal/src/uart/peripheral.rs#L277) used to configure the UART registers for a given `wanted_baudrate`, the variable `baud_div_int` and `baud_div_frac` are both `u16`.
This causes an integer overflow leads to a panic when executing the following line at `64 * baud_div_int`:
https://github.com/rp-rs/rp-hal/blob/8f6cbd85c255bcd902e32bf41f33be85cd532ca1/rp2040-hal/src/uart/peripheral.rs#L301
This PR modifies it to be similar to the official SDK implementation :
https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_uart/uart.c#L73-L99
I'm currently using my own fork of `rp2040-pac` as the current implementation of …
> Fix integer over-flow on using low UART baudrate 

- rp2040-hal/src/lib.rs
The documentation texts are mostly copied from the corresponding comments in Cargo.toml, so this mainly improves visibility of those explanations by showing them on docs.rs.
The wording could surely be improved, but I'll leave that for another day.
> Add documentation for crate features to lib.rs

- clippy.toml
- rp2040-hal/src/dma/bidirectional.rs
- rp2040-hal/src/gpio/mod.rs
- rp2040-hal/src/pio.rs
- rp2040-hal/src/rtc/datetime_no_deps.rs
Today I learned about the `avoid-breaking-exported-api = false` clippy config.
https://doc.rust-lang.org/stable/clippy/lint_configuration.html?highlight=avoid-breaking-exported-api#avoid-breaking-exported-api
While a clippy warning probably is not a good justification for a breaking change, such warnings can be useful to avoid issues in new APIs.
The number of issues clipply flags for existing APIs is managable, so I propose adding that config, and add matching allow annotations to override warnings in the current API.
> Activate clippy checks on exported APIs

- rp2040-hal/examples/dma.rs
- rp2040-hal/examples/mem_to_mem_dma.rs
- rp2040-hal/src/dma/mod.rs
This example is intended to show basic DMA usage, without involving any peripherals.
It is similar to the [hello_dma.c](https://github.com/raspberrypi/pico-examples/blob/master/dma/hello_dma/hello_dma.c) example from official Raspberry Pi.
The structure is taken from the already existing [spi_dma example](https://github.com/rp-rs/rp-hal/blob/main/rp2040-hal/examples/spi_dma.rs).
Also fixing a typo in DMA docs.
> Add basic DMA example, memory to memory transfer

- .github/workflows/build_and_test.yml
- .github/workflows/clippy.yml
- .github/workflows/rustfmt.yml
- on-target-tests/Cargo.toml
Use `cargo-hack` to save some maintenance effort on CI/test maintenance by auto-discovering features and optional deps.
Use `cargo-install` to benefit from its caching feature and shorten CI run time.
> Improve testing

- rp2040-hal/src/dma/bidirectional.rs
- rp2040-hal/src/dma/double_buffer.rs
- rp2040-hal/src/dma/single_buffer.rs
- rp2040-hal/src/dma/single_channel.rs
Just rearranged my fork so I can add more features through different branches, sorry about having to re-create my PR.
> Byteswapping config

- rp2040-hal/examples/spi.rs
- rp2040-hal/examples/spi_dma.rs
- rp2040-hal/src/spi.rs
```
error[E0308]: mismatched types
--> src/main.rs:72:9
|
68  |     let mut spi = spi.init(
|                       ---- arguments to this method are incorrect
...
72  |         &embedded_hal::spi::MODE_0,
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `embedded_hal::spi::Mode`, found `Mode`
|
= note: `Mode` and `embedded_hal::spi::Mode` have similar names, but are actually distinct types
```
I was getting an error.  Not sure if these are the right changes but fixes the issue for me.  Potentially the feature conditionals could be tidied up.
> Fix Spi for EH1 alpha

- rp2040-hal/examples/blinky.rs
- rp2040-hal/src/timer.rs
Make `Timer` a cloneable type:
We don't support de-initializing a `Timer` anyways. And once it's initialized, all operations on it are either read-only, or already wrapped in the separate alarm structures.
Therefore, we can safely allow for `Timer` to be cloned, and implement the delay functions directly on it. That makes the API more ergonomic.
Co-authored-by: Wilfried Chauveau <wilfried.chauveau@ithinuel.me>
> Cloneable timer

- rp2040-hal/src/spi.rs
Add `impl From<&embedded_hal::spi::Mode> for Mode`.
This unbreaks code like this, which did work with rp2040-hal 0.8:
```
let spi = spi.init(
&mut pac.RESETS,
clocks.peripheral_clock.freq(),
16_000_000u32.Hz(),
&embedded_hal::spi::MODE_0,
);
```
> Minor usability improvement

- rp2040-hal/CHANGELOG.md
- rp2040-hal/src/multicore.rs
> Remove the requirement for multicore tasks to never return

- on-target-tests/Cargo.toml
- rp2040-hal/Cargo.toml
We already introduced some breaking changes so we might as well already increase the version number on git a while before the release.
That may help users using the git repo be warned about more upcoming breakage.
> bump hal's version

- rp2040-hal/CHANGELOG.md
- rp2040-hal/examples/blinky.rs
- rp2040-hal/examples/vector_table.rs
- rp2040-hal/src/timer.rs
> Make sure clocks are initialized before creating a Timer

- rp2040-hal/src/spi.rs
I'm pretty sure this is a typo right?
> Fix typo using `impl_write!`, 22 should be 12

- rp2040-hal/src/spi.rs
- rp2040-hal/src/usb.rs
> Fix URL of pico_usb_serial example

- rp2040-hal/src/adc.rs
Renamed the fields to make their purpose clearer.
> Rename field names of struct AdcPin

- rp2040-hal/Cargo.toml
- rp2040-hal/examples/adc_fifo_irq.rs
- rp2040-hal/examples/adc_fifo_poll.rs
- rp2040-hal/src/adc.rs
An attempt to come up with an API for the ADC in free-running mode.
Inspired by #326.
Overview of changes:
- Adds two new structs to the `adc` module: `FreeRunning` and `Fifo` (EDIT: naming changed to `AdcFifoBuilder` and `AdcFifo`)
- `FreeRunning` represents the `Adc` configuration for free-running mode:
- it is obtained by calling `adc.free_running()`
- it provides methods to configure things that only make sense in this mode: set clock_divider (DIV.INT, DIV.FRAC), set round_robin (CS.RROBIN), ...
- and methods to start enable the FIFO and start the capture (CS.START_MANY): `start_fifo`, `start_fifo_with_dma(thresh)`
- the `Fifo` struct represents the ADC Fifo while capture is running:
- it is returned by the `start_*` methods from `FreeRunning`
- `fifo.len()` and `fifo.read()` give …
> ADC free-running mode & FIFO

- rp2040-hal/src/usb.rs
Previous value was mistakenly set to 0x3F(6 bit) instead of 0x7F(7 bit)
> Fix of usb device address mask

- CODE_OF_CONDUCT.md
- README.md
I did a quick check of other links.  http://citizencodeofconduct.org is also broken right now but seems like it is maybe temporary.
> Fix broken link to team list

- rp2040-hal/src/lib.rs
Due to https://github.com/rust-lang/rust/issues/112308, the public re-export of the pac will trigger a missing docs warning in rust 1.71.0.
This is bogus, as the doc string would not be shown in the rendered docs anyway. However, the warning would be annoying, so add a short doc string to the item.
> Avoid missing docs warning on pub extern crate

- rp2040-hal/Cargo.toml
- rp2040-hal/examples/adc_fifo_dma.rs
- rp2040-hal/examples/adc_fifo_irq.rs
- rp2040-hal/src/adc.rs
DMA support for free-running ADC capture.
The basic API looks like this:
```
// without DMA:
let adc_fifo = adc.build_fifo()
.something_something()
.start();
do_something_with_fifo(adc_fifo);
// with DMA:
let adc_fifo = adc.build_fifo()
.something_something()
.enable_dma()
.prepare();
let transfer = dma::single_buffer::Config::new(dma.ch0, adc_fifo.dma_read_target(), some_write_target).start();
adc_fifo.resume();
do_something_else_while_dma_does_all_the_work();
```
To enable this functionality, the following methods were added:
- `AdcFifoBuilder::enable_dma`: sets `FCS.DREQ_EN = 1` and `FCS.THRESH = 1`
- `AdcFifoBuilder::prepare`: same as `start`, but does not set `CS.START_MANY` just yet
- `AdcFifo::resume` / `AdcFifo::pause`: control if capturing is active (`CS.START_MANY`) without …
> ADC fifo DMA

- rp2040-hal/src/pwm/mod.rs
Hello,
Here is an implementation of WriteTarget for PWM slices.
In my opinion this respects the safety requirements described in #621.
The implementation uses `u16` as type for the writes to the top register, which will cause the reserved upper bits to be written to by the same value. Is this problematic? I thought of using a type that has the upper 16 bits set to zero, but this would contradict the safety requirements of the `Word` trait.
> Implement WriteTarget for PWM top and cc registers.

- rp2040-hal-macros/Cargo.toml
Right now this doesn't improve anything: While other dependencies still use syn version 1, it just causes both versions to be built, increasing the build time. So we might not yet want to merge this.
Once dependencies start to migrate to version 2, we should do so as well, to complete the migration to version 2 as quickly as possible.
> Upgrade syn to version 2.0

- rp2040-hal/examples/adc_fifo_dma.rs
- rp2040-hal/src/dma/single_channel.rs
My motivation for this change is that the first time I encountered the `listen_irq*` methods, the name invoked a misleading picture in my mind:
`channel.listen_irq0()` sounds like the channel is "listening" for the IRQ, and will do something once it triggers.
That's not the case though: calling this method will cause the channel to *trigger* the interrupt -- some other part of the program must do the listening.
Reasons to call it `enable_irq*` / `disable_irq*` instead:
- The corresponding function in pico-sdk is called `dma_channel_set_irqX_enabled`
- The INTEx register documentation also uses this terminology: "Interrupt Enables for IRQ X"
> Rename `dma::SingleChannel::listen_irq*` to `enable_irq*`

- rp2040-hal/src/usb.rs
Lifetimes should have been `'_` and not static.
`get_buf_mut` created a mutable reference from an immutable reference.
SAFETY annotation has also been added.
> Fix lifetimes and mutability of `get_buf` and `get_buf_mut`

- rp2040-hal/src/multicore.rs
See https://github.com/raspberrypi/pico-sdk/issues/993 for an explanation why the old code happens to work in practice, due to the reset value of the register.
Thanks to @9names for mentioning this issue in the pico-sdk repo.
Fixes #641
> Fix calculation of MPU RBAR value

- .github/workflows/build_and_test.yml
This should avoid random breakage with newer nightly versions
> Use fixed version nightly-2023-06-27 for cargo udeps

- rp2040-hal/src/pio.rs
I noticed that both irq0 and irq1 said PIO0 and then I looked a bit closer.
> Correct PIO::irq[01] documentation

- rp2040-hal/src/gpio/mod.rs
This is inside a macro, so it's only tested when this macro is used. Therefore, it only failed when testing rp-hal-boards: https://github.com/rp-rs/rp-hal-boards/actions/runs/5754010918/job/15598412621
> Fix an import in a doc comment

- .github/workflows/build_and_test.yml
The latest version of cargo-hack does no longer compile with our MSRV, see https://github.com/rp-rs/rp-hal/actions/runs/5776719346/job/15656129384?pr=660
Version 0.5.28 did work:
https://github.com/rp-rs/rp-hal/actions/runs/5767856400/job/15640265924o
Therefore, lock the version we install in our workflow to that version.
> Fix version of cargo-hack to 0.5.28

- rp2040-hal/src/rom_data.rs
This patch fixes a typo in rom_data.rs
closes #672
> Fix typo in rom_data.rs

- rp2040-hal/src/dma/mod.rs
- rp2040-hal/src/pio.rs
- rp2040-hal/src/spi.rs
- rp2040-hal/src/uart/reader.rs
- rp2040-hal/src/uart/writer.rs
This implements the "mark traits as unsafe" part of https://github.com/rp-rs/rp-hal/issues/620#issuecomment-1558767880
> Mark ReadTarget and WriteTarget as unsafe

- rp2040-hal/src/i2c.rs
As discussed in #678, the hardware does not support zero-length read/write transactions.
> Document limitations of I2C hardware

- rp2040-hal/src/adc.rs
- rp2040-hal/src/pwm/mod.rs
Those trait impls were introduced after #621 was opened and were therefore not covered by that PR.
> Fix build errors introduced by #621

- rp2040-hal/src/lib.rs
Possible implementation of #564
> Implement reset() and halt() functions

- rp2040-hal/src/pll.rs
While setting up a custom clock with `refdiv = 2`, I noticed it's post division frequency was half it's expected value; it seems that when making a new `PhaseLockedLoopDevice`, division of the reference frequency by `refdiv` occurs twice, which I assume is unintentional.
> Removed second division by `refdiv`

- rp2040-hal/src/rtc/mod.rs
- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/vector_table.rs
We sometimes use &mut to guarantee exclusive access to some ressource, where the compiler can't see that such a guarantee is needed for soundness. Therefore, warnings about needles &mut references should not be generated.
Without this change, starting from rust 1.73 (currently in beta), the following clippy warnings will be generated:
```
warning: this argument is a mutable reference, but not used mutably 
--> rp2040-hal/src/rtc/mod.rs:57:17 
| 
57 |         resets: &mut RESETS, 
|                 ^^^^^^^^^^^ help: consider changing to: `&RESETS` 
| 
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_pass_by_ref_mut 
= note: `#[warn(clippy::needless_pass_by_ref_mut)]` on by default 
warning: this argument is a mutable reference, but …
```
> Disable clippy lint needless_pass_by_ref_mut

- rp2040-hal/src/adc.rs
The name conflicts with the public trait method OneShot::read. This isn't an issue with correct programs, as rustc just uses the visible function when called from other crates.
But if you forget importing OneShot, you get a confusing error message:
```
error[E0624]: method `read` is private
--> rp2040-hal/examples/adc.rs:116:45
|
116 |         let temp_sens_adc_counts: u16 = adc.read(&mut temperature_sensor).unwrap();
|                                             ^^^^ private method
|
::: /home/jan/rp2040/rp-rs/rp-hal/rp2040-hal/src/adc.rs:302:5
|
302 |     fn read(&mut self, chan: u8) -> u16 {
|     ----------------------------------- private method defined here
|
= help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in …
```
> Rename private function Adc::read to Adc::inner_read

- rp2040-hal/src/gpio/mod.rs
> Implement InputPin for all pin configurations via .as_input() function

- rp2040-hal/Cargo.toml
- rp2040-hal/examples/gpio_dyn_pin_array.rs
#585 changed how GPIO worked, and the changelog hinted that it made it easier to use Pins in arrays but did not include any examples, doc-examples, or code snippets that tell you how to do it.
This example should at least provide some hints to new embedded rustaceans on how to use this feature.
> Add example using GPIO DynPin

- rp2040-hal/examples/i2c.rs
- rp2040-hal/src/i2c.rs
- rp2040-hal/src/i2c/peripheral.rs
Hopefully, this covers some of the short commings reported in https://github.com/rp-rs/rp-hal/issues/690.
> Improve documentation of the i2c peripheral driver & improve i2c example

- .cargo/config
- .github/workflows/build_and_test.yml
- README.md
- on-target-tests/.cargo/config.toml
- on-target-tests/Cargo.toml
- on-target-tests/README.md
- on-target-tests/run_tests.bat
- on-target-tests/run_tests.sh
Probe-run is deprecated in favour of probe-rs: https://ferrous-systems.com/blog/probe-run-deprecation/
~The on-target tests still use probe-run, they fail with probe-rs:~ on-target tests migrated to probe-rs, as well. See 3rd commit for details.
```
$ CARGO_TARGET_THUMBV6M_NONE_EABI_RUNNER="probe-rs run" cargo test --test dma_m2m_u8 -- --chip rp2040
Finished test [optimized + debuginfo] target(s) in 0.03s
Running tests/dma_m2m_u8.rs (target/thumbv6m-none-eabi/debug/deps/dma_m2m_u8-ebcd141c1ecc1d99)
Erasing sectors ✔ [00:00:00] [###############################################################################################################################################################] 12.00 KiB/12.00 KiB @ 45.03 KiB/s (eta 0s )
Programming pages   ✔ [00:00:00] …
```
> Replace probe-run by probe-rs

- rp2040-hal/src/i2c/controller.rs
Implements the WriteIter and WriteIterRead traits from embedded-hal.
> Implement WriteIter and WriteIterRead

- rp2040-hal/src/spi.rs
Documents the types of the `Spi` struct and brushes up a few other docs.
> Improve Spi device/peripheral docs

- rp2040-hal/examples/adc.rs
- rp2040-hal/examples/i2c.rs
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/examples/spi.rs
- rp2040-hal/examples/spi_dma.rs
- rp2040-hal/examples/uart.rs
- rp2040-hal/examples/uart_dma.rs
- rp2040-hal/examples/vector_table.rs
- rp2040-hal/examples/watchdog.rs
- rp2040-hal/src/lib.rs
Closes #572
I also had a quick look for other crates to re-export:
One candidate would be `embedded-hal`, but I think a re-export is not appropriate there: That crate is, in general, not used to access features of `rp2040-hal`, but it's the other way around: Some driver expects a type implementing a trait from `embedded-hal`, and `rp2040-hal` provides that type. In that chase, the needed version of `embedded-hal` is selected by the driver, not by `rp2040-hal`, and a re-export would not help with that.
There are probably more, but it needs to be checked manually which dependencies are actually used in exposed APIs. I don't want to re-export something unnecessarily.
On other small change: I hid the re-export of `paste` from the docs. It's only there because it's used in macros provided by …
> Re-export fugit

- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/writer.rs
The `uart_is_busy()` method returns `true` as long as the UART is busy transmitting data.  It will return `false` once all bits (including stop bits) have been transmitted.
> Add uart_is_busy() method for UART devices

- README.md
> Mention linker flags in README

- rp2040-hal/src/uart/writer.rs
The UART is not completely flushed when the TX FIFO becomes empty, as long as there are still bits left in the TX shift register.
Therefore, transmit_flushed() should check the busy bit, not the txfe bit.
> Fix UART transmit_flushed method

- rp2040-hal/src/i2c.rs
According to cargo semver-checks, that's necessary to stay semver compatible with v0.9.0
> Make i2c::controller pub again

- rp2040-hal/src/pio.rs
It's different from the reset value, which can easily be missed when porting code from the C SDK.
> Document default value for ShiftDirection

- rp2040-hal/CHANGELOG.md
- rp2040-hal/src/pll.rs
The previously used settings used a VCO clock of 480MHz, which is outside the valid range (750MHz - 1600MHz) given by the datasheet since revision 1.8.
There are several valid VCO values, and there is a tradeoff between lower jitter and lower power consumption. So it's not obvious which value would be the best default.
Instead of doing our own guesswork, use the same value as the C SDK: https://github.com/raspberrypi/pico-sdk/pull/869/files
This patch only changes the default value, but doesn't update the input validation. So it's still possible to manually specify a VCO frequency outside the updated range, as long as it's in the more lenient range specified by older datasheet revisions, 400MHz - 1600MHz.
> Use same USB_PLL default setting as the C SDK

- rp2040-hal/src/pwm/mod.rs
This is needed to be able to have e.g. 3 PWM slices that are in phase, but may use different duty cycles.
Example usage: `pwm_slices.enable_simultaneous(0b0000_0111);`
Demo
----
Phases between slices before this fix, using
```
pwm0.enable();
pwm1.enable();
```
Phases between slices after this fix, using
```
pwm_slices.enable_simultaneous(0b0000_0111);
```
> Add function to enable multiple PWM slices at the same time

- .github/workflows/build_and_test.yml
- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/src/usb.rs
Next usb-device release has some changes around isochronous endpoint type.
(only to be merged once the new version of usb-device gets published)
> Update usb-device implementation.

- rp2040-hal/src/spi.rs
In the case where the pins are shared with some other function, one should be able to free them up from the Spi instance. Also useful if the SPI0 will be switched between two configurations, therefore calling `Spi::new` and `Spi::free` back and forth.
Example use case is Pololu's 3Pi+ Robot which reuses SPI0 configured with different pins.
Reference C support: https://github.com/pololu/pololu-3pi-2040-robot/tree/master/c/pololu_3pi_2040_robot
WIP Rust support in `rp-hal-boards`: https://github.com/SCingolani/rp-hal-boards/tree/pololu-threepi-plus-2040
> Make `Spi::free` also free up the pins

- rp2040-hal/src/i2c.rs
This reverts commit 0e0506ce94a5347c9972c72714953885108cea4b.
To be applied before the next minor release (0.10.0). (Or after creating a 0.9.x release branch, if we want to do so)
> Revert "Make i2c::controller pub again"

- rp2040-hal/src/pio.rs
This allows getting the IRQ with `pio.irq::<IRQn>()`, where IRQn is a type generic.
This is a minor breaking change. I struggled for a while trying to get something similar working with the existing const generic, without success.
> Make PIO IRQ IDs into ZSTs

- rp2040-hal/src/rtc/mod.rs
- rp2040-hal/src/usb.rs
The RealTimeClock works great, but it takes ownership of the `rtc_clock` field in the `ClockManager`, which makes it invalid (partial move).
Moreover, the `RealTimeClock` struct doesn't allow freeing `rtc_clock`, the `new` function doesn't do anything about it, so the instance is destroyed.
Following the model of other functions present in the HAL for clock configuration (such as `setup_pll_blocking` or `configure_clock` from ClockManger), I modified the parameter so that it was a reference.
#724
Thanks for this brilliant HAL!
> Fix RealTimeClock & UsbBus ownership

- rp2040-hal/src/gpio/func.rs
This missing impl effectively prevented anyone from using a `Pin<_, DynFunction, _>`.
> add missing ValidFunction implementation for DynFunction.

- rp2040-hal/examples/pio_blink.rs
- rp2040-hal/examples/pio_dma.rs
- rp2040-hal/examples/pio_proc_blink.rs
- rp2040-hal/examples/pio_side_set.rs
- rp2040-hal/examples/pio_synchronized.rs
- rp2040-hal/src/pio.rs
The existing function `from_program` uses the "wrong" shift direction, the default is different from what the RP2040 does. This is confusing and can lead to difficult to debug errors. (This is how this difference was found.)
To avoid a subtle breaking change by just fixing the default, introduce a new function `from_installed_program` with the correct default value, and deprecate the old one.
> Add from_installed_program with correct shift direction

- rp2040-hal/Cargo.toml
- rp2040-hal/examples/pwm_blink.rs
- rp2040-hal/examples/pwm_blink_embedded_hal_1.rs
- rp2040-hal/src/pwm/mod.rs
Also add a new example pwm_blink_embedded_hal_1 which uses this trait, to have a minimal test case.
> Implement embedded_hal::pwm::SetDutyCycle of embedded-hal 1.0

- rp2040-hal/src/sio.rs
According to https://doc.rust-lang.org/stable/reference/inline-assembly.html#directives-support the assembly directive `.macro` is not part of the supported subset.
The reference further explains: "The result of using other directives is assembler-specific (and may cause an error, or may be accepted as-is)"
So while it obviously works right now, it might cause issues in future versions of rust. Not sure if this would be avoided as a breaking change. To be on the safe side, replace asm macros by rust macros.
> Replace asm macros by rust macros

- rp2040-hal/Cargo.toml
- rp2040-hal/src/lib.rs
This is supported since rust 1.60, and makes available features more visible.
> Use namespaced (`dep:`) features for optional dependencies

- rp2040-hal/src/pwm/mod.rs
A TOP value of 0xffff is incompatible with true 100% duty cycle. Therefore, the default TOP value is reduced to 0xfffe, and a warning regarding the 0xffff value is added the documentation of `set_top`.
The value returned by get_max_duty is corrected to be TOP + 1, if possible.
Closes #735
> PWM: Set TOP to 0xfffe by default and fix get_max_duty

- rp2040-hal/CHANGELOG.md
- rp2040-hal/src/xosc.rs
This works the same way as PICO_XOSC_STARTUP_DELAY_MULTIPLIER in the Pico SDK
Closes #745
> Add startup_delay_multiplier parameter to xosc initialization

- rp2040-hal/examples/i2c.rs
- rp2040-hal/src/i2c.rs
It is possible to skip this check by using `hal::I2C::i2c0_unchecked(...)` or `hal::I2C::i2c1_unchecked(...)`, but the default constructor functions now only accept pins with activated PullUp.
Fixes #690.
> Ensure that i2c pins have PullUp activated

- rp2040-hal/examples/adc.rs
- rp2040-hal/examples/adc_fifo_dma.rs
- rp2040-hal/examples/adc_fifo_irq.rs
- rp2040-hal/examples/adc_fifo_poll.rs
- rp2040-hal/examples/blinky.rs
- rp2040-hal/examples/dht11.rs
- rp2040-hal/examples/gpio_dyn_pin_array.rs
- rp2040-hal/examples/gpio_in_out.rs
- rp2040-hal/examples/gpio_irq_example.rs
- rp2040-hal/examples/i2c.rs
- rp2040-hal/examples/lcd_display.rs
- rp2040-hal/examples/mem_to_mem_dma.rs
- rp2040-hal/examples/multicore_fifo_blink.rs
- rp2040-hal/examples/multicore_polyblink.rs
- rp2040-hal/examples/pwm_blink.rs
- rp2040-hal/examples/pwm_blink_embedded_hal_1.rs
- rp2040-hal/examples/pwm_irq_input.rs
- rp2040-hal/examples/rom_funcs.rs
- rp2040-hal/examples/rtc_irq_example.rs
- rp2040-hal/examples/spi.rs
- rp2040-hal/examples/spi_dma.rs
- rp2040-hal/examples/uart.rs
- rp2040-hal/examples/uart_dma.rs
- rp2040-hal/examples/vector_table.rs
- rp2040-hal/examples/watchdog.rs
- rp2040-hal/src/clocks/mod.rs
> Implement defmt formatting and Debug for clocks::InitError

- rp2040-hal/src/uart/reader.rs
A break condition is also a framing error. As it is the more specific code, return the break error.
> Properly report break conditions

- .cargo/config
- .github/workflows/build_and_test.yml
- on-target-tests/Cargo.toml
- on-target-tests/README.md
- on-target-tests/build.rs
- on-target-tests/tests/i2c_loopback.rs
- on-target-tests/tests/i2c_loopback_async.rs
- on-target-tests/tests/i2c_tests/blocking.rs
- on-target-tests/tests/i2c_tests/mod.rs
- on-target-tests/tests/i2c_tests/non_blocking.rs
- rp2040-hal/Cargo.toml
- rp2040-hal/examples/i2c.rs
- rp2040-hal/examples/i2c_async.rs
- rp2040-hal/examples/i2c_async_cancelled.rs
- rp2040-hal/src/async_utils.rs
- rp2040-hal/src/i2c.rs
- rp2040-hal/src/i2c/controller.rs
- rp2040-hal/src/i2c/controller/non_blocking.rs
- rp2040-hal/src/i2c/peripheral.rs
- rp2040-hal/src/lib.rs
This re-introduces the async.await i2c driver that was once remove because of requiring nightly at the time.
Now that the necessary features have been stabilized, we can all enjoy a bit of async.await-ness :)
- #761
- #762
- #763
- #764
> [i2c] (re)introduce async.await implementation

- .github/workflows/build_and_test.yml
- on-target-tests/Cargo.toml
- on-target-tests/README.md
- on-target-tests/tests/i2c_loopback.rs
- on-target-tests/tests/i2c_tests/blocking.rs
- on-target-tests/tests/i2c_tests/mod.rs
- rp2040-hal/examples/i2c.rs
- rp2040-hal/src/i2c.rs
- rp2040-hal/src/i2c/controller.rs
- rp2040-hal/src/i2c/peripheral.rs
Requires:
- #761
- #762
- #763
> [i2c]  add on target tests for blocking i2c

- rp2040-hal/Cargo.toml
- rp2040-hal/examples/alloc.rs
I found it interesting how using an allocator with the rp-pico would work, so i build this little example, which is derived from the blinking led example.
I couldn't find any constant indicating a possible heap size in the hal, but i may have overlooked it.
I was mainly inspired by this repository: [alloc-cortex-m](https://github.com/rust-embedded/alloc-cortex-m)
Feedback is appreciated :)
> Added an example for using alloc-cortex-m

- rp2040-hal/Cargo.toml
this makes it easier to find the crate, esp. when filtering by category.
note that this will only become visible on crates.io once a new release has been published.
> `Cargo.toml`: add `categories` & `keywords`

- on-target-tests/Cargo.toml
- on-target-tests/tests/i2c_loopback_async.rs
- on-target-tests/tests/i2c_tests/non_blocking.rs
- rp2040-hal/Cargo.toml
- rp2040-hal/src/i2c/controller.rs
- rp2040-hal/src/i2c/controller/non_blocking.rs
- rp2040-hal/src/lib.rs
Requires:
- #761
- #762
- #763
- #764
- #747
> [i2c] Implement i2c-write-iter traits

- rp2040-hal/src/pll.rs
This completes the change introduced in #688 to update the valid range for VCO’s frequency.
Note: this change was left off until now because it was a breaking change.
> Update VCO minimum frequency

- rp2040-hal/CHANGELOG.md
- rp2040-hal/examples/adc.rs
- rp2040-hal/examples/adc_fifo_dma.rs
- rp2040-hal/examples/adc_fifo_irq.rs
- rp2040-hal/examples/adc_fifo_poll.rs
- rp2040-hal/src/adc.rs
- Renamed `AdcFifoBuilder::prepare(self)` to `AdcFifoBuilder::start_paused(self)` as it more clearly describes what it does.
- Added new trait `AdcChannel`, implemented by `AdcPin` and `TempSense`. Main difference to embedded hal's `Channel` type: `AdcChannel::channel(&self)` has the `&self` parameter, so it can be sanely implemented for `DynPin`.
- Added `Adc::free_running(&mut self, pin: &dyn AdcChannel)` to configure free-running mode on an ADC
- Added `Adc::wait_ready(&self)` and `Adc::is_ready(&self)` mainly for completeness (not sure if they are useful?)
- Added `AdcFifo::trigger(&mut self)` to be able to use `AdcFifo` without free-running mode
- Added `AdcFifo::is_ready(&self)`
- Added more doc comments
> Allow free-running ADC mode without FIFO

- rp2040-hal/src/adc.rs
- rp2040-hal/src/pio.rs
- rp2040-hal/src/spi.rs
- rp2040-hal/src/uart/reader.rs
- rp2040-hal/src/uart/writer.rs
This is slightly less error prone than `as *const _`.
> Use as_ptr() to retrieve pointer to register

- on-target-tests/Cargo.toml
- on-target-tests/tests/gpio.rs
- rp2040-hal/CHANGELOG.md
- rp2040-hal/src/gpio/mod.rs
- rp2040-hal/src/gpio/pin.rs
This is meant to fix #754.
~Not yet tested at all!~
Tested using on-target-tests.
> Turn off input_enable for ADC capable pins

- rp2040-hal/src/adc.rs
- rp2040-hal/src/dma/single_channel.rs
- rp2040-hal/src/float/mod.rs
- rp2040-hal/src/gpio/func.rs
- rp2040-hal/src/pwm/mod.rs
- rp2040-hal/src/timer.rs
- rp2040-hal/src/watchdog.rs
Fix several warnings reported by clippy (in nightly) and cargo doc (in stable) about unused code, dangling links etc.
> Fix several clippy and cargo doc warnings

- rp2040-hal/src/async_utils.rs
- rp2040-hal/src/clocks/clock_sources.rs
- rp2040-hal/src/multicore.rs
- rp2040-hal/src/pll.rs
- rp2040-hal/src/rtc/datetime.rs
- rp2040-hal/src/sio.rs
- rp2040-hal/src/usb.rs
- rp2040-hal/src/vector_table.rs
- rp2040-hal/src/xosc.rs
I'm not sure how useful these `Default` implementations are in practice. But I like the pattern "if there is a non-argument new() constructor, `Default` should be implemented as well".
https://rust-lang.github.io/rust-clippy/master/index.html#/new_without_default
> Fix some more nightly clippy warnings

- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
- Update CHANGELOG.md (should be up to date as of commit a9b91ea)
- Set version to 0.10.0 in preparation for the release
> Preparations for release 0.10.0

- rp2040-hal/src/timer.rs
Our MSRV is 1.75, and div_ceil is available since 1.73
> Simplify ceiling division in delay calculation

- rp2040-hal/src/rom_data.rs
The current return argument for `float_to_fix64()` is `f32`, which doesn't make sense and is at odds with the definition in the pico SDK. This PR replaces it with the correct type.
The function as exposed by the SDK is here:
https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_float/include/pico/float.h#L44
It returns an `int64`, so I've updated rom_data.rs to match. I tested this on my pico by converting a small set of `f32`s to fix64 with the change in this PR, then back through `fix64_to_float()` and the values match up.
This is a breaking change, though given that the return argument was both the wrong type and the wrong size, I'm not sure if anyone could really have used this function as it currently stands.
Additionally, the function descriptions for fcos, fsin, …
> Fix `float_to_fix64` return value & f32 trig function doc corrections

- rp2040-hal/src/pio.rs
Rather than always assuming PIO DMA transfers are u32, also allow u16 and u8. The hardware will replicate sub-32-bit transfers across the whole 32 bit word, which is the same as accessing the Tx/Rx fifo directly.
This implements a rather general type-level description of a transfer, so maybe it should go in the `dma` module rather than being `pio` specific?
This fixes #554
> Enable transfer size of PIO DMA to be specified

- rp2040-hal/src/dma/mod.rs
- rp2040-hal/src/pio.rs
This is a generic way to represent a DMA channel transfer size at the type level, so move it to `dma` where it can be used more generally.
Followup to #788
> Move TransferSize to `dma` module

- rp2040-hal/src/pio.rs
As noticed in https://github.com/rp-rs/rp-hal/pull/791, the existing deprecation note doesn't mention that `from_installed_program` isn't an identical replacement for `from_program`. That can misguide people to just replace the function call without noticing the changed shift direction.
> Slightly improve deprecation note on from_program

- rp2040-hal/src/lib.rs
> Fix debugging after halt()

- rp2040-hal/src/uart/reader.rs
- rp2040-hal/src/uart/writer.rs
The embedde_io traits were already implemented for the unsplit peripheral, https://github.com/rp-rs/rp-hal/blob/main/rp2040-hal/src/uart/peripheral.rs#L421-L445.
This adds implementations for the Reader and Writer types.
> Implement embedded_io traits for Reader/Writer

- rp2040-hal/src/adc.rs
Currently, the `Adc::read` typically gets stuck in an infinite loop when running in `OneShot` configuration. This bug was introduced in version 0.10 and does not exist on prior versions. It results from the `CS` register being read once outside of the wait loop and then never again.
> Fix oneshot adc read waiting indefinitely

- on-target-tests/tests/gpio.rs
- rp2040-hal/CHANGELOG.md
- rp2040-hal/src/adc.rs
Also includes the test case from #800 and a changelog entry.
> Backport pull request #799

- rp2040-hal/src/gpio/pin/pin_sealed.rs
Don't accidentally transmute from `&&Reg<_>` to `&Reg<_>`, and make types in transmutes explicit to avoid such issues in future.
> Fix transmutes

- rp2040-hal/src/gpio/mod.rs
There is a bug in the implementation of  `set_low()` and `set_high()` functions in `OutputPin` for embedded-hal 1.0. The call to `set_low()` doesn't have any effect because `set_output_enable_override(OutputEnableOverride::Disable)` was set inside `new`
The fix aligns the implementation to be the same as used for embedded-hal 0.2 traits
> Fix set_low() and set_high() implementation for OutputPin

- rp2040-hal/src/dma/single_buffer.rs
- rp2040-hal/src/dma/single_channel.rs
This MR implements support for aborting DMA transfers, following 2.5.5.3 of the datasheet and #722.
This should close #722.
> Add support for aborting DMA transfers

- README.md
- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/src/gpio/mod.rs
- rp2040-hal/src/gpio/pin/pin_sealed.rs
This merge requests backports a few fixes from main, and makes the necessary changes for a v0.10.2 release.
> Prepare v0.10.2

- rp2040-hal/src/gpio/pin_group.rs
Fixes WritePinHList::write_mask. Before, it always returned 0, making all writes to pin groups ineffective.
> Fix writing to pin groups

- rp2040-hal/src/timer.rs
This allows to remove the lifetime parameter from CountDown. As Timer is zero-sized, this should also reduce the size of CountDown.
Due to the removal of the lifetime parameter, this is a breaking change.
Closes #216
> Base CountDown on Timer instead of &Timer

- .github/workflows/build_and_test.yml
Speeds up the CI as then we don't have to wait for them to compile.
> Install cargo-udeps and cargo-hack as binaries.

- on-target-tests/tests/gpio.rs
I was scrolling through the code and I thought I could fix this while I was at it. I just extended the tests in `gpio.rs` a _tiny_ bit.
Replaced the uses of `assert!(x == y)` with `assert_eq!()`, so it was more clear which pin was wrong when tests failed.
Also added checks for `group.set(...)`, `group.set_u32(...)`, on top of the existing `group.toggle()`
Switch hex numbers to binary to make it easier to read the bits.
> Extend tests in `gpio::check_pin_groups()`

- .cargo/config.toml
It doesn't work anyway, see https://github.com/rust-lang/rust/pull/124712
> Remove -Cinline-threshold=5 option from config.toml

- on-target-tests/tests/gpio.rs
This test just hangs without the fix from #799. Is there an easy way to set a timeout in defmt-tests? Of course the test case could configure the watchdog, but that would quite some boilerplate to an otherwise simple test case.
Still better than no test at all.
> This adds a test-case covering the fix from PR #799

- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/reader.rs
Closes: #782
It would be preferable to avoid the code duplication between `UartPeripheral` and `Reader`. However, before starting a bigger code restructuring, I'd like to get some feedback on the general approach:
- Is it the right trade-off to reserve some memory in `UartPeripheral` and `Reader` to store the read error?
- What are alternative approaches?
- Ignore the issue, accept discarding bytes on error. (Might be acceptable, assuming that serial errors are rare and the received message is probably garbled anyway. Should be clearly documented.)
- Don't implement `embedded_io::Read` at all. (Breaking change, lost functionality, IMHO not acceptable)
- Don't implement `embedded_io::Read` directly on `UartPeripheral` and `Reader`, but instead on a separate wrapper type. (Breaking change, …
> Avoid discarding already read bytes on error

- .github/workflows/build_and_test.yml
- memory.x
- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/examples/binary_info_demo.rs
- rp2040-hal/src/binary_info/consts.rs
- rp2040-hal/src/binary_info/macros.rs
- rp2040-hal/src/binary_info/mod.rs
- rp2040-hal/src/binary_info/types.rs
- rp2040-hal/src/lib.rs
Adds support for picotool compatible binary info. Bumps MSRV to 1.77.
```console
$ cargo build --release --example binary_info_demo --features=critical-section-impl,binary-info
Compiling rp2040-hal v0.10.0 (/home/jonathan/Documents/github/rp-hal/rp2040-hal)
Finished `release` profile [optimized] target(s) in 2.24s
$ picotool info ./target/thumbv6m-none-eabi/release/examples/binary_info_demo -t elf --all
File ./target/thumbv6m-none-eabi/release/examples/binary_info_demo:
Program Information
name:          rp2040-hal Binary Info Example
version:       0.10.0
web site:      https://github.com/rp-rs/rp-hal
description:   A GPIO blinky with extra metadata.
binary start:  0x10000000
Fixed Pin Information
none
Build Information
pico_board:        pico
build attributes:  release
```
The `static` …
> Adds binary info block support.

- rp2040-hal/src/spi.rs
There are other drivers in the wild (uboot, zephyr) that set the format without disabling the peripheral, so we’ll assume it is fine to do so.
> spi: move set_format to all states

- rp2040-hal/CHANGELOG.md
- rp2040-hal/src/uart/writer.rs
embedded_io::Write::write(buf) should not block until the full buffer was written. Instead, it should only block until at least one byte was written.
(See https://github.com/rp-rs/rp-hal/pull/837#issuecomment-2305371353)
> Let UART write return some bytes were written

- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/reader.rs
- rp2040-hal/src/uart/writer.rs
Implements  `embedded_io::ReadReady` and `WriteReady` traits for split and unsplit uart peripheral in terms of the already existing functions for checking if the uart is ready to read or write :rocket: 
Solves #836
> implement `embedded_io::ReadReady` and `WriteReady` traits for uart peripheral

- rp235x-hal/src/spi.rs
The updates from #831 were only applied to rp2040-hal.
This patch ports them to rp235x-hal.
> Port SPI changes from rp2040-hal to rp235x-hal

- rp2040-hal-examples/src/bin/pio_side_set.rs
- rp235x-hal-examples/src/bin/pio_side_set.rs
The rp2040 and rp235x example of pio_side_set have diverged a bit. Port the changes made to the rp235x back to rp2040, where applicable.
Also update a comment, as suggested in https://github.com/rp-rs/pio-rs/issues/62
> Sync pio_side_set examples

- rp2040-hal-examples/Cargo.toml
- rp2040-hal-examples/src/bin/uart_loopback.rs
- rp2040-hal/src/uart/peripheral.rs
- rp2040-hal/src/uart/reader.rs
- rp235x-hal-examples/Cargo.toml
- rp235x-hal-examples/riscv_examples.txt
- rp235x-hal-examples/src/bin/rom_funcs.rs
- rp235x-hal-examples/src/bin/uart_loopback.rs
- rp235x-hal/src/uart/peripheral.rs
- rp235x-hal/src/uart/reader.rs
- rp235x-hal/src/uart/writer.rs
The updates from #798, #837 and #838 were only applied to rp2040-hal. This patch ports them to rp235x-hal.
> Port UART updates to rp235x-hal

- on-target-tests/Cargo.toml
- on-target-tests/tests/i2c_tests/mod.rs
- on-target-tests/tests/i2c_tests/non_blocking.rs
- on-target-tests/tests/i2c_tests/test_executor.rs
This has some advantages:
- no longer depend on nostd_async, which has known issues (https://github.com/sammhicks/nostd_async/issues/4) and looks rather unmaintained
- the custom executor can check that the waker is only called when expected (currently only implemented as some defmt logging, but this can be improved)
- in case of problems, it is easier to debug than a full-fledged executor
The new dependency on `once_cell` can be removed with rust 1.82.0, which makes `Waker::from_raw` callable from `const` contexts.
> Replace nostd_async with a simple test executor

- rp2040-hal-examples/Cargo.toml
- rp2040-hal-examples/src/bin/i2c_async.rs
- rp2040-hal-examples/src/bin/i2c_async_cancelled.rs
- rp235x-hal-examples/Cargo.toml
- rp235x-hal-examples/src/bin/i2c_async.rs
- rp235x-hal-examples/src/bin/i2c_async_cancelled.rs
For the needs of our examples, a much simpler executor would suffice. But it doesn't hurt to use a full-blown executor, the code doesn't become more complicated that way.
> Use embassy-executor instead of nostd_async

- rp235x-hal-examples/memory.x
- rp235x-hal-examples/rp235x_riscv.x
The `.boot_info` section was missing from the RP2350 linker scripts (both Arm and RISC-V).
This adds it back, tucking it next to where the start block lives, as the BI must be in the first 4K of flash.
Closes #853
> Add missing binary info to 2350 linker scripts.

- .github/workflows/rp2040_hal_examples.yml
- .github/workflows/rp235x_hal_examples_arm.yml
This should catch bugs like https://github.com/rp-rs/rp-hal/issues/853
> Run picotool step in github action

- rp2040-hal/src/spi.rs
- rp235x-hal/src/spi.rs
Based on #832, rebased and ported to rp235x-hal.
> spi: remove undesired parameter to `set_format`

- rp-binary-info/src/lib.rs
- rp235x-hal-examples/src/bin/block_loop.rs
Since rust 1.82.0, addr_of is no longer unsafe:
https://github.com/rust-lang/rust/pull/125834
Just removing the unsafe statement would break builds with older versions of rust. Instead, allow the unused_unsafe lint.
> Fix warning with rust 1.82.0

- on-target-tests/Cargo.toml
- rp2040-hal-examples/Cargo.toml
- rp2040-hal/Cargo.toml
- rp235x-hal-examples/Cargo.toml
- rp235x-hal/Cargo.toml
Older versions contain a soundness bug.
> Update critical-section dependency to version 1.2.0

- on-target-tests/Cargo.toml
- rp-binary-info/src/lib.rs
- rp2040-hal-examples/Cargo.toml
- rp2040-hal/Cargo.toml
- rp2040-hal/src/gpio/func.rs
- rp2040-hal/src/gpio/mod.rs
- rp2040-hal/src/gpio/pin.rs
- rp2040-hal/src/gpio/pull.rs
- rp2040-hal/src/sio.rs
- rp2040-hal/src/spi.rs
- rp235x-hal-examples/Cargo.toml
- rp235x-hal-examples/src/bin/block_loop.rs
- rp235x-hal/Cargo.toml
- rp235x-hal/src/spi.rs
Is there a general problem adding these derives to more structures? I am trying to use a driver for a LCD display, and I can not unwrap the returned result structure because Debug is not implemented by the pin structures used by the driver. This applies to both the concrete pins and the downgraded pins.
These were only the derives I needed to pass both dyn pins and concrete pins to the driver. There are probably a lot more structures where t his derive could be added.
> Add debug derive for the GPIO structures

- rp235x-hal/src/pio.rs
fixes #867 
Please let me know if something is not to your liking
> feat: add support for PIO `in_count`

- rp235x-hal-examples/.cargo/config.toml
- rp235x-hal-examples/README.md
Create aliases build-arm run-arm build-riscv and run-riscv in
.cargo/config.toml. With these defined you can now use the alias which
will be converted to the full target name:
cargo build-arm   -> cargo build --target thumbv8m.main-none-eabihf
cargo run-arm     -> cargo run --target thumbv8m.main-none-eabihf
cargo build-riscv -> cargo build --target riscv32imac-unknown-none-elf
cargo run-risv    -> cargo run --target riscv32imac-unknown-none-elf
Append --release parameter to do release builds and runs. For example:
cargo run-riscv --release ->
cargo run --target riscv32imac-unknown-none-elf --release
feat: Make it easier to specify target architecture
Create aliases build-arm run-arm build-riscv and run-riscv in .cargo/config.toml. With these defined you can now use the alias which will …
> feat: Make it easier to specify target architecture

- rp235x-hal-examples/src/bin/rom_funcs.rs
- rp235x-hal/src/rom_data.rs
Implements a nice safe wrapper for `get_sys_info` as described in #839 .
> Add a nice wrapper for `get_sys_info`

- rp2040-hal/src/adc.rs
- rp2040-hal/src/gpio/mod.rs
- rp2040-hal/src/i2c.rs
- rp2040-hal/src/multicore.rs
- rp2040-hal/src/uart/mod.rs
- rp2040-hal/src/watchdog.rs
Hello,
Here a comment fix :
`https://github.com/rp-rs/rp-hal/tree/main/rp2040-hal/examples/` is outdated
replaced by:
`https://github.com/rp-rs/rp-hal/tree/main/rp2040-hal-examples/`
🚀
> Update RP2040-hal example urls

- rp235x-hal/src/gpio/func.rs
- rp235x-hal/src/gpio/pin.rs
Implement support for XipCS1 pin function which is necessary to implement support for external ram or flash.
Note: The rp235x-pac is missing function select definition for XipCS1:
https://github.com/rp-rs/rp235x-pac/blob/main/svd/RP2350.yaml#L321
But `FUNCSEL_A::GPCK` has the same value (9). We should add a variant specific for XipCS1.
> Implement support for XipCS1 pin function.

- rp2040-hal-examples/Cargo.toml
- rp2040-hal/CHANGELOG.md
- rp2040-hal/Cargo.toml
- rp2040-hal/README.md
Bump to 0.11.0 in:
* `rp2040-hal/Cargo.toml`
* The dependency on `rp2040-hal` in `rp2040-hal-examples/Cargo.toml`
* `rp2040-hal/CHANGELOG.md`
* `rp2040-hal/README.md`
> Prepare release 0.11.0

- rp2040-hal-examples/src/bin/gpin.rs
- rp2040-hal/src/clocks/clock_sources.rs
- rp2040-hal/src/clocks/mod.rs
- rp2040-hal/src/gpin.rs
- rp2040-hal/src/lib.rs
Fixes https://github.com/rp-rs/rp-hal/issues/879 by adding a `GpIn0` and `GpIn1` struct, which implement `ClockSource`, such that a user can call `configure_clocks` for these clock inputs and use the safe clock switching logic already built in.
I tried keeping the gpin.rs style kind of similar to other pin related interfaces (e.g. I2C), let me know if this aligns to your code style :)
I've renamed the type from `GPin` to `GpIn`, I believe it's a "General Purpose (clock) INput", hence the `gpin` name in the datasheet (similarly, there's also a `gpout`).
I've also provided an example which I ran on an RPi Pico, on an oscilloscope I could see that the pulses the example code drives are in sync with the provided clock :tada:
> Add support for external clocks on gpin GPIO pins

- .github/workflows/rp2040_hal_examples.yml
- .github/workflows/rp235x_hal_examples_arm.yml
Currently, it's not available in testing.
> Install picotool from debian/unstable instead of testing

- rp2040-hal/src/adc.rs
- rp2040-hal/src/dma/single_channel.rs
- rp2040-hal/src/float/conv.rs
- rp2040-hal/src/i2c.rs
- rp235x-hal-examples/src/bin/rom_funcs.rs
- rp235x-hal/src/adc.rs
- rp235x-hal/src/block.rs
- rp235x-hal/src/dma/single_channel.rs
- rp235x-hal/src/i2c.rs
- rp235x-hal/src/powman.rs
With current beta (1.85.0-beta.1), rustc introduced new clippy warnings regarding non-obvious operator precedence:
```
warning: operator precedence can trip the unwary
--> src/adc.rs:876:14
|
876 |         Self(1 << pins.0.channel() | 1 << pins.1.channel())
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider parenthesizing your expression: `(1 << pins.0.channel()) | (1 << pins.1.channel())`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#precedence
= note: `#[warn(clippy::precedence)]` on by default
```
These can be easily fixed by adding some parentheses, as shown in this pull request.
I'm not sure if this really helps readability. Alternatively, we could silence clippy for this warning. …
> Fix clippy::precedence warning in current beta

- rp2040-hal/src/multicore.rs
- rp235x-hal/src/multicore.rs
The derived formatting looks like `StackAllocation { mem: 0x20000040..0x20004040 }`. While this exposes an implementation detail (the naming of the `mem` field), I think it's good enough for debug output.
Closes #888
> Derive Debug and defmt::Format for StackAllocation

- rp235x-hal-examples/src/bin/rom_funcs.rs
Before:
```
Reading OTP_DATA
RP2350 Package ID: 0xa9e3aa32
RP2350 Device ID : 0xafa893f7
Reading OTP_DATA_RAW
RP2350 Package ID: 0x001faa32 0x0031a9e3
RP2350 Device ID : 0x002093f7 0x001aafa8
get_sys_info(CHIP_INFO/0x0001)
RP2350 Package ID: 0x00000000
RP2350 Device ID : 0xa9e3aa32
RP2350 Wafer ID  : 0xafa893f7
```
After:
```
Reading OTP_DATA
RP2350 Device ID: 0xa9e3aa32
RP2350 Wafer ID : 0xafa893f7
Reading OTP_DATA_RAW
RP2350 Device ID: 0x001faa32 0x0031a9e3
RP2350 Wafer ID : 0x002093f7 0x001aafa8
get_sys_info(CHIP_INFO/0x0001)
RP2350 Package  : 0x00000000 (QFN80, but wrong on A2 stepping)
RP2350 Device ID: 0xa9e3aa32
RP2350 Wafer ID : 0xafa893f7
```
> Make output of rom_funcs example a bit more consistent

- on-target-tests/Cargo.toml
- on-target-tests/tests/dma_dyn.rs
- on-target-tests/tests/dma_m2m_u16.rs
- on-target-tests/tests/dma_m2m_u32.rs
- on-target-tests/tests/dma_m2m_u8.rs
- on-target-tests/tests/dma_spi_loopback_u16.rs
- on-target-tests/tests/dma_spi_loopback_u8.rs
- on-target-tests/tests/gpio.rs
- on-target-tests/tests/i2c_loopback.rs
- on-target-tests/tests/i2c_loopback_async.rs
- on-target-tests/tests/i2c_tests/blocking.rs
- on-target-tests/tests/i2c_tests/non_blocking.rs
- on-target-tests/tests/init/mod.rs
- on-target-tests/tests/multicore.rs
- rp235x-hal/src/multicore.rs
Fixes #897
Also adds an on-target test to verify that atomics are working, and fixes initialization between on-target tests.
> Set EXTEXCLALL when enabling multi-core operation

- .github/workflows/on_target_tests.yml
- .github/workflows/rp2040_hal.yml
- .github/workflows/rp2040_hal_examples.yml
- .github/workflows/rp235x_hal_arm.yml
- .github/workflows/rp235x_hal_examples_arm.yml
- .github/workflows/rp235x_hal_examples_riscv.yml
- .github/workflows/rp235x_hal_riscv.yml
- .github/workflows/rp_binary_info.yml
- .github/workflows/rp_hal_common.yml
- rp235x-hal/src/arch.rs
- use current versions of "cargo-udeps" and of rust nightly to fix errors regarding Cargo.lock version
- update runner image to ubuntu-24.04 (precompiled updated version of cargo-udeps had library issues with ubuntu-20.04, and ubuntu-20.04 is being deprecated anyway, see https://github.com/actions/runner-images/issues/11101
- fix another clippy lint that triggered another CI pipeline error
See https://github.com/rp-rs/rp-hal/actions/runs/13615045124/job/38057015487 for a pipeline failing without this fix.
> Fix cargo udeps

- rp235x-hal-examples/Cargo.toml
- rp235x-hal/CHANGELOG.md
- rp235x-hal/Cargo.toml
- rp235x-hal/README.md
> Prepare release of rp235x-hal 0.3.0

- rp235x-hal/src/dma/mod.rs
RP235x has 16 DMA channels, but rp235x-hal currently only exposes 12 of them. I assume this is left over from rp2040-hal.
> Update number of DMA channels from 12 to 16 (on RP235x)

- rp235x-hal-examples/src/bin/pio_putget.rs
- rp235x-hal/src/pio.rs
I added support for the new (as of RP235x) RXFIFO PUT and GET modes. These give a PIO state machine direct access to words in RXFIFO.
I also added an example which demonstrates writing to and reading from RXFIFO, though I don't know if it's super necessary.
Please make any changes/corrections :)
> Add support for PUT and GET FIFO modes

- rp2040-hal/src/pwm/mod.rs
- rp235x-hal/src/pwm/mod.rs
Issue https://github.com/rp-rs/rp-hal/issues/907 showed that SetDutyCycle was difficult to use because its implementation depends on whether it's an A or B channel.
This change avoids the requirement to manually specify the channel type.
It also removes some unnecessary code duplication.
> Implement SetDutyCycle generically on ChannelId

- rp235x-hal-examples/riscv_examples.txt
- rp235x-hal-examples/rp235x_riscv.x
- rp235x-hal-examples/src/bin/gpio_irq_example.rs
- rp235x-hal-examples/src/bin/i2c_async.rs
- rp235x-hal-examples/src/bin/i2c_async_cancelled.rs
- rp235x-hal-examples/src/bin/powman_test.rs
- rp235x-hal-examples/src/bin/pwm_irq_input.rs
- rp235x-hal/src/arch.rs
- rp235x-hal/src/lib.rs
- rp235x-hal/src/sio.rs
- rp235x-hal/src/xh3irq.rs
) Adds an Xh3irq controller driver
) Adds a default `MachineExternal` handler which uses the Xh3irq to run whichever interrupts are pending
) Adds a bunch of interrupt control stuff to `hal::arch`
) Fixes the `powman_test` example to use the new interrupt APIs - it now works on RISC-V and Arm.
Tested `powman_test` on a Pico 2 in both `riscv32imac-unknown-none-elf` and `thumbv8m.main-none-eabihf`.
> Interrupts on RISC-V

- rp235x-hal/src/arch.rs
The function was added in f98b41e1, after I made the branch merged in #847. Github ran CI on the branch, and it passed, but it didn't pass once the branch was merged into main because this new function wasn't exported.
> Add missing enable_coprocessors to arch mod.

- rp2040-hal-examples/src/bin/adc_fifo_dma.rs
- rp2040-hal-examples/src/bin/adc_fifo_irq.rs
- rp2040-hal-examples/src/bin/adc_fifo_poll.rs
- rp2040-hal-examples/src/bin/spi_eh_bus.rs
- rp2040-hal-examples/src/bin/uart_loopback.rs
- rp2040-hal/src/i2c.rs
- rp235x-hal-examples/src/bin/adc_fifo_dma.rs
- rp235x-hal-examples/src/bin/adc_fifo_irq.rs
- rp235x-hal-examples/src/bin/adc_fifo_poll.rs
- rp235x-hal-examples/src/bin/float_test.rs
- rp235x-hal-examples/src/bin/powman_test.rs
- rp235x-hal-examples/src/bin/rom_funcs.rs
- rp235x-hal-examples/src/bin/uart_loopback.rs
- rp235x-hal-examples/src/bin/usb.rs
- rp235x-hal/src/i2c.rs
- rp235x-hal/src/powman.rs
Current beta (rustc 1.88.0-beta.3) warns about `clippy::uninlined_format_args` in calls to `writeln!`. Avoid that warning by inlining the arguments.
> Fix clippy warnings in current beta

- rp-binary-info/Cargo.toml
- rp-binary-info/src/lib.rs
- rp-binary-info/src/macros.rs
- rp-binary-info/src/types.rs
- rp2040-hal-examples/memory.x
- rp2040-hal-examples/src/bin/binary_info_demo.rs
- rp2040-hal/Cargo.toml
- rp235x-hal-examples/Cargo.toml
- rp235x-hal-examples/memory.x
- rp235x-hal-examples/rp235x_riscv.x
- rp235x-hal-examples/src/bin/binary_info_demo.rs
- rp235x-hal/Cargo.toml
Unfortunately the fix to rp_binary_end is a breaking change. And as rp-binary-info is re-exported by the HALs, it will also be a breaking change for them.
I wonder if it's a good idea to re-export this crate from the HALs. If we have a breaking change anyway, we can also use it to remove the re-export. Then future breaking changes to rp-binary-info won't infect the HALs, again.
As far as I can see there's no necessity for the re-export, it's a pure convenience thing. And in this case, the difference between using the re-exports and adding a direct dependency on rp-binary-info is minimal.
> Fix rp_binary_end

- rp235x-hal/src/clocks/mod.rs
- rp235x-hal/src/gpio/func.rs
- rp235x-hal/src/gpio/mod.rs
- rp235x-hal/src/gpio/pin.rs
- rp235x-hal/src/hstx.rs
- rp235x-hal/src/hstx/pins.rs
- rp235x-hal/src/lib.rs
There is not much to abstract in HSTX, but it still nice to have it in HAL for resets, pins etc. There are many questionable decisions made here for sure (including, but not limited to pinout), and I would be happy to hear your feedback.
I have an example using this module in [my repo](https://github.com/OYTIS/rp235x-hstx-example), but it's too bulky for rp235x-hal-examples - maybe a rework of [ST7789 example from pico-examples](https://github.com/raspberrypi/pico-examples/blob/master/hstx/spi_lcd/hstx_spi_lcd.c) will work?
PIO coupling is out of scope for this PR.
> Add HSTX support

- README.md
- on-target-tests/.cargo/config.toml
- rp2040-hal-examples/.cargo/config.toml
- rp2040-hal-examples/README.md
elf2uf2-rs seems to be unmaintained, and as of Rust 1.89 [rejects valid ELF files](https://github.com/JoNil/elf2uf2-rs/issues/40) due to an overly strict check of the ELF header. Picotool is maintained by Raspberry Pi and does not have this problem.
This commit changes guide-level explanation in the root and RP2040 examples READMEs, and the runner in .cargo/config.toml files, to picotool.
Some wording around the flashing process as "creating a UF2 file" was changed as picotool can flash directly from an ELF file with the appropriate command-line flag. Information about deliberately creating a UF2 file has been kept.
In addition, the root README now directs people to rp-binary-info rather than stating that picotool compatible "binary info" is unsupported.
---
**A question**: Previously the …
> Remove elf2uf2-rs in favour of picotool

- README.md
Make sure we mention both HALs here, plus some of the other packages we have going on.
I've also dialled back on "Raspberry Silicon" because although that was used in the headline of the [launch blog](https://www.raspberrypi.com/news/raspberry-pi-silicon-pico-now-on-sale/), they don't seem to use the term much now.
> Make the top level README reflect that there are two HALs now.

- rp235x-hal/CHANGELOG.md
- rp235x-hal/src/reboot.rs
I saw @thejpster 's avatar when filing a PR into defmt and realised I hadn't gotten around to filing this PR. This goes back to the errata I reported here: https://github.com/raspberrypi/pico-feedback/issues/466, which was subsequently incorporated into the [datasheet](https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf), page 397 in section `5.4.8.24`, `p0` is now flags, while `p1` is the gpio.
I use the embassy hal, which doesn't provide a wrapper, when I was setting up bootsel rebooting for picotool, I couldn't figure out how to disable that mass storage device and ultimately also tried the reboot from this HAL, which also didn't work. Only when I tried the pico-sdk reboot function did things start working, which led to the discovery of the above issue. Fixing it here …
> RP2350: Fix handling of flags in BOOTSEL reboot calls.

- .github/workflows/rp2040_hal_examples.yml
- .github/workflows/rp235x_hal_examples_arm.yml
I don't even remember why I added it in the first place. May have been a plain cut & paste error.
> Don't install libxml2-utils in CI pipeline

- rp235x-hal/src/timer.rs
in previous version, there was possibility to have 2 timers but only 4 alarms total, here are changes, that makes possible to configure up to 4 alarms for each timer
> both timers support up to 4 alarms

- rp235x-hal/src/multicore.rs
Stack checking on the RP235x arm cores via msplim is pretty straightforward - lets turn that on when launching code on core1.
> Add stack checking via msplim for rp235x core1
